#!/usr/bin/perl

# Xania player archiving utility. 

require 5;
require File::stat;
use POSIX;
use File::Find;
use Carp;
my $numdel = 0;

sub main {
    my $LOGNAME = $ENV{LOGNAME};
    my $remotename = "REMOTE_USER";
    my $remotehost = "xania.org";
    my $remotepath = "/some/remote/path";
    $nowtime =  strftime( "%B-%d-%Y-%H.%M.%S", gmtime );
	print( "Xania player archiving utility executed by \"$LOGNAME\" at $nowtime\n\r" );
    
    chdir( ".." );
    my $tarfile = "player-$nowtime.tar.gz";
    my $tarstring = "tar zcf $tarfile player/";
    print( "1 - creating a tar archive: $tarstring\n\r" );    
    system( $tarstring );
    chdir( "player" );
    print( "2 - deleting old level 1 characters...\n\r" );
    find(\&wanted, '.');
    print( "Trashed $numdel newbies.\n\r" );
    chdir( ".." ); # go back to where tar file is stashed
    print( "3 - copying backup to remote host using 'scp'\n\r" );
    print( "Remote user name[$remotename]: " );
    while(<>){
	if( length( $_ ) > 1 ) {
	    chop( $_ );
	    $remotename = $_;
	    last;
	}
	last;
    }
    print( "Remote host name[$remotehost]: " );
    while(<>){

	if( length( $_ ) > 1 ) {
	    chop( $_ );
	    $remotehost = $_;
	    last;
	}
	last;
    }
    print( "Remote directory[$remotepath]: " );
    while(<>){

	if( length( $_ ) > 1 ) {
	    chop( $_ );
	    $remotepath = $_;
	    last;
	}
	last;
    }
    
    my $copystring = "scp $tarfile $remotename\@$remotehost:$remotepath/$tarfile";
    system( "$copystring" );
    print( "Thank you!\n\r" );
    exit;    
}

sub is_newbie {
    my $savestring = $_;
    my $ret = 0;
    open( plr_fh, $_ ) or carp( "Couldn't open file \"$_\".\n\r" );
    input: while(<plr_fh>) {
	if( /^Levl\s*(\d+).*$/ ) {
	    if( $1 == 1 ) {
		$ret = 1;
		last input;
	    }
	}
    }
    close( plr_fh);
    $_ = $savestring;
    return $ret;
}

sub wanted {
    (($dev,$ino,$mode,$nlink,$uid,$gid) = lstat($_)) and
	(int(-M _) > 30) and  is_newbie($_)==1 and unlink( $_ ) and $numdel++;
}

main();


