/*************************************************************************/
/*  Xania (M)ulti(U)ser(D)ungeon server source code                      */
/*  (C) 2021 Xania Development Team                                      */
/*  See merc.h and README for original copyrights                        */
/*************************************************************************/
#include "SkillTables.hpp"
#include "magic.h"
#include "merc.h"

/*
 * The skill and spell table.
 * Slot numbers must never be changed as they appear in #OBJECTS sections.
 */
#define SLOT(n) n

const struct skill_type skill_table[MAX_SKILL] = {

    /*
     * Magic spells.
     */

    {"reserved",
     {99, 99, 99, 99},
     {99, 99, 99, 99},
     0,
     TAR_IGNORE,
     Position::Type::Standing,
     nullptr,
     SLOT(0),
     0,
     0,
     "",
     "",
     nullptr,
     nullptr,
     0},

    {"acid blast",
     {28, 60, 60, 60},
     {1, 1, 2, 2},
     spell_acid_blast,
     TAR_CHAR_OFFENSIVE,
     Position::Type::Fighting,
     nullptr,
     SLOT(70),
     20,
     12,
     "acid blast",
     "!Acid Blast!",
     nullptr,
     nullptr,
     0},

    {"octarine fire",
     {40, 60, 60, 60},
     {2, 3, 3, 3},
     spell_octarine_fire,
     TAR_CHAR_OFFENSIVE,
     Position::Type::Fighting,
     &gsn_octarine_fire,
     SLOT(99),
     50,
     12,
     "octarine fire",
     "The octarine fire earths to the ground.",
     check_dispel,
     "$n's octarine outline discharges into the ground.",
     0},

    {"armor",
     {7, 2, 3, 5},
     {1, 1, 2, 2},
     spell_armor,
     TAR_CHAR_DEFENSIVE,
     Position::Type::Standing,
     nullptr,
     SLOT(1),
     5,
     12,
     "",
     "You feel less protected.",
     check_dispel,
     "$n is no longer protected.",
     0},

    {"bless",
     {60, 7, 9, 60},
     {1, 1, 2, 2},
     spell_bless,
     TAR_CHAR_DEFENSIVE,
     Position::Type::Standing,
     &gsn_bless,
     SLOT(3),
     5,
     12,
     "",
     "You feel less righteous.",
     check_dispel,
     "$n no longer has divine favour.",
     0},

    {"blindness",
     {12, 8, 11, 15},
     {1, 1, 2, 2},
     spell_blindness,
     TAR_CHAR_OFFENSIVE,
     Position::Type::Fighting,
     &gsn_blindness,
     SLOT(4),
     5,
     12,
     "",
     "You can see again.",
     check_dispel,
     "$n can see again.",
     AFF_BLIND},

    {"burning hands",
     {7, 60, 60, 60},
     {1, 1, 2, 2},
     spell_burning_hands,
     TAR_CHAR_OFFENSIVE,
     Position::Type::Fighting,
     nullptr,
     SLOT(5),
     15,
     12,
     "burning hands",
     "!Burning Hands!",
     nullptr,
     nullptr,
     0},

    {"call lightning",
     {26, 18, 22, 29},
     {1, 1, 2, 2},
     spell_call_lightning,
     TAR_IGNORE,
     Position::Type::Fighting,
     nullptr,
     SLOT(6),
     15,
     12,
     "lightning bolt",
     "!Call Lightning!",
     nullptr,
     nullptr,
     0},

    {"calm",
     {60, 16, 20, 60},
     {1, 1, 2, 2},
     spell_calm,
     TAR_IGNORE,
     Position::Type::Fighting,
     nullptr,
     SLOT(509),
     30,
     12,
     "",
     "You have lost your peace of mind.",
     check_dispel,
     "$n no longer looks so peaceful.",
     AFF_CALM},

    {"cancellation",
     {18, 26, 34, 34},
     {1, 1, 2, 2},
     spell_cancellation,
     TAR_CHAR_DEFENSIVE,
     Position::Type::Fighting,
     nullptr,
     SLOT(507),
     20,
     12,
     "",
     "!cancellation!",
     nullptr,
     nullptr,
     0},

    {"cause critical",
     {60, 13, 19, 60},
     {1, 1, 2, 2},
     spell_cause_critical,
     TAR_CHAR_OFFENSIVE,
     Position::Type::Fighting,
     nullptr,
     SLOT(63),
     20,
     12,
     "spell",
     "!Cause Critical!",
     nullptr,
     nullptr,
     0},

    {"cause light",
     {60, 1, 3, 60},
     {1, 1, 2, 2},
     spell_cause_light,
     TAR_CHAR_OFFENSIVE,
     Position::Type::Fighting,
     nullptr,
     SLOT(62),
     15,
     12,
     "spell",
     "!Cause Light!",
     nullptr,
     nullptr,
     0},

    {"cause serious",
     {60, 7, 10, 60},
     {1, 1, 2, 2},
     spell_cause_serious,
     TAR_CHAR_OFFENSIVE,
     Position::Type::Fighting,
     nullptr,
     SLOT(64),
     17,
     12,
     "spell",
     "!Cause Serious!",
     nullptr,
     nullptr,
     0},

    {"chain lightning",
     {33, 60, 60, 60},
     {1, 1, 2, 2},
     spell_chain_lightning,
     TAR_CHAR_OFFENSIVE,
     Position::Type::Fighting,
     nullptr,
     SLOT(500),
     45,
     14,
     "lightning",
     "!Chain Lightning!",
     nullptr,
     nullptr,
     0},

    {"change sex",
     {60, 60, 60, 60},
     {1, 1, 2, 2},
     spell_change_sex,
     TAR_CHAR_DEFENSIVE,
     Position::Type::Fighting,
     nullptr,
     SLOT(82),
     15,
     12,
     "",
     "Your body feels familiar again.",
     check_dispel,
     "$n looks more like $r again.",
     0},

    {"charm person",
     {20, 60, 25, 60},
     {1, 1, 2, 2},
     spell_charm_person,
     TAR_CHAR_OFFENSIVE,
     Position::Type::Standing,
     &gsn_charm_person,
     SLOT(7),
     5,
     12,
     "",
     "You feel more self-confident.",
     check_dispel,
     "$n regains $s free will.",
     0},

    {"chill touch",
     {4, 60, 60, 60},
     {1, 1, 2, 2},
     spell_chill_touch,
     TAR_CHAR_OFFENSIVE,
     Position::Type::Fighting,
     nullptr,
     SLOT(8),
     15,
     12,
     "chilling touch",
     "You feel less cold.",
     check_dispel,
     "$n looks warmer.",
     0},

    {"colour spray",
     {16, 60, 60, 60},
     {1, 1, 2, 2},
     spell_colour_spray,
     TAR_CHAR_OFFENSIVE,
     Position::Type::Fighting,
     nullptr,
     SLOT(10),
     15,
     12,
     "colour spray",
     "!Colour Spray!",
     nullptr,
     nullptr,
     0},

    {"continual light",
     {6, 4, 6, 9},
     {1, 1, 2, 2},
     spell_continual_light,
     TAR_IGNORE,
     Position::Type::Standing,
     nullptr,
     SLOT(57),
     7,
     12,
     "",
     "!Continual Light!",
     nullptr,
     nullptr,
     0},

    {"control weather",
     {15, 19, 22, 28},
     {1, 1, 2, 2},
     spell_control_weather,
     TAR_IGNORE,
     Position::Type::Standing,
     nullptr,
     SLOT(11),
     25,
     12,
     "",
     "!Control Weather!",
     nullptr,
     nullptr,
     0},

    {"create food",
     {10, 5, 11, 11},
     {1, 1, 2, 2},
     spell_create_food,
     TAR_IGNORE,
     Position::Type::Standing,
     nullptr,
     SLOT(12),
     5,
     12,
     "",
     "!Create Food!",
     nullptr,
     nullptr,
     0},

    {"create spring",
     {14, 17, 22, 22},
     {1, 1, 2, 2},
     spell_create_spring,
     TAR_IGNORE,
     Position::Type::Standing,
     nullptr,
     SLOT(80),
     20,
     12,
     "",
     "!Create Spring!",
     nullptr,
     nullptr,
     0},

    {"create water",
     {8, 3, 12, 11},
     {1, 1, 2, 2},
     spell_create_water,
     TAR_OBJ_INV,
     Position::Type::Standing,
     nullptr,
     SLOT(13),
     5,
     12,
     "",
     "!Create Water!",
     nullptr,
     nullptr,
     0},

    {"cure blindness",
     {60, 6, 8, 10},
     {1, 1, 2, 2},
     spell_cure_blindness,
     TAR_CHAR_DEFENSIVE,
     Position::Type::Fighting,
     nullptr,
     SLOT(14),
     5,
     12,
     "",
     "!Cure Blindness!",
     nullptr,
     nullptr,
     0},

    {"cure critical",
     {60, 13, 17, 60},
     {1, 1, 2, 2},
     spell_cure_critical,
     TAR_CHAR_DEFENSIVE,
     Position::Type::Fighting,
     nullptr,
     SLOT(15),
     20,
     12,
     "",
     "!Cure Critical!",
     nullptr,
     nullptr,
     0},

    {"cure disease",
     {60, 13, 14, 17},
     {1, 1, 2, 2},
     spell_cure_disease,
     TAR_CHAR_DEFENSIVE,
     Position::Type::Standing,
     nullptr,
     SLOT(501),
     20,
     12,
     "",
     "!Cure Disease!",
     nullptr,
     nullptr,
     0},

    {"cure light",
     {60, 1, 3, 60},
     {1, 1, 2, 2},
     spell_cure_light,
     TAR_CHAR_DEFENSIVE,
     Position::Type::Fighting,
     nullptr,
     SLOT(16),
     10,
     12,
     "",
     "!Cure Light!",
     nullptr,
     nullptr,
     0},

    {"cure poison",
     {60, 14, 16, 19},
     {1, 1, 2, 2},
     spell_cure_poison,
     TAR_CHAR_DEFENSIVE,
     Position::Type::Standing,
     nullptr,
     SLOT(43),
     5,
     12,
     "",
     "!Cure Poison!",
     nullptr,
     nullptr,
     0},

    {"cure serious",
     {60, 7, 10, 60},
     {1, 1, 2, 2},
     spell_cure_serious,
     TAR_CHAR_DEFENSIVE,
     Position::Type::Fighting,
     nullptr,
     SLOT(61),
     15,
     12,
     "",
     "!Cure Serious!",
     nullptr,
     nullptr,
     0},

    {"curse",
     {18, 18, 26, 22},
     {1, 1, 2, 2},
     spell_curse,
     TAR_CHAR_OFFENSIVE,
     Position::Type::Fighting,
     &gsn_curse,
     SLOT(17),
     20,
     12,
     "curse",
     "The curse wears off.",
     check_dispel,
     "$n looks relieved.",
     0},

    {"exorcise",
     {60, 34, 40, 60},
     {1, 1, 2, 2},
     spell_exorcise,
     TAR_CHAR_OFFENSIVE,
     Position::Type::Fighting,
     nullptr,
     SLOT(506),
     20,
     12,
     "exorcism",
     "!exorcise!",
     nullptr,
     nullptr,
     0},

    {"demonfire",
     {60, 34, 40, 60},
     {1, 1, 2, 2},
     spell_demonfire,
     TAR_CHAR_OFFENSIVE,
     Position::Type::Fighting,
     nullptr,
     SLOT(505),
     20,
     12,
     "malice",
     "!Demonfire!",
     nullptr,
     nullptr,
     0},

    {"detect evil",
     {12, 4, 60, 60},
     {1, 1, 2, 2},
     spell_detect_evil,
     TAR_CHAR_SELF,
     Position::Type::Standing,
     nullptr,
     SLOT(18),
     5,
     12,
     "",
     "The red in your vision disappears.",
     check_dispel,
     "$n's sensitivity to evil fades.",
     AFF_DETECT_EVIL},

    {"detect hidden",
     {15, 11, 60, 60},
     {1, 1, 2, 2},
     spell_detect_hidden,
     TAR_CHAR_SELF,
     Position::Type::Standing,
     nullptr,
     SLOT(44),
     5,
     12,
     "",
     "You feel less aware of your suroundings.",
     check_dispel,
     "$n looks less alert.",
     AFF_DETECT_HIDDEN},

    {"detect invis",
     {3, 8, 60, 60},
     {1, 1, 2, 2},
     spell_detect_invis,
     TAR_CHAR_SELF,
     Position::Type::Standing,
     nullptr,
     SLOT(19),
     5,
     12,
     "",
     "You no longer see invisible objects.",
     check_dispel,
     "$n's eyes stop sparkling.",
     AFF_DETECT_INVIS},

    {"detect magic",
     {2, 6, 60, 60},
     {1, 1, 2, 2},
     spell_detect_magic,
     TAR_CHAR_SELF,
     Position::Type::Standing,
     nullptr,
     SLOT(20),
     5,
     12,
     "",
     "The detect magic wears off.",
     check_dispel,
     "$n's sensitivity to magic fades.",
     AFF_DETECT_MAGIC},

    {"detect poison",
     {15, 7, 60, 60},
     {1, 1, 2, 2},
     spell_detect_poison,
     TAR_OBJ_INV,
     Position::Type::Standing,
     nullptr,
     SLOT(21),
     5,
     12,
     "",
     "!Detect Poison!",
     check_dispel,
     "$n's sensitivity to poison fades.",
     0},

    {"dispel evil",
     {60, 15, 20, 60},
     {1, 1, 2, 2},
     spell_dispel_evil,
     TAR_CHAR_OFFENSIVE,
     Position::Type::Fighting,
     nullptr,
     SLOT(22),
     15,
     12,
     "dispel evil",
     "!Dispel Evil!",
     nullptr,
     nullptr,
     0},

    {"dispel good",
     {60, 15, 20, 60},
     {1, 1, 2, 2},
     spell_dispel_good,
     TAR_CHAR_OFFENSIVE,
     Position::Type::Fighting,
     nullptr,
     SLOT(322),
     15,
     12,
     "dispel good",
     "!Dispel Good!",
     nullptr,
     nullptr,
     0},

    {"dispel magic",
     {16, 24, 30, 30},
     {1, 1, 2, 2},
     spell_dispel_magic,
     TAR_CHAR_OFFENSIVE,
     Position::Type::Fighting,
     nullptr,
     SLOT(59),
     15,
     12,
     "",
     "!Dispel Magic!",
     nullptr,
     nullptr,
     0},

    {"earthquake",
     {60, 10, 14, 60},
     {1, 1, 2, 2},
     spell_earthquake,
     TAR_IGNORE,
     Position::Type::Fighting,
     nullptr,
     SLOT(23),
     15,
     12,
     "earthquake",
     "!Earthquake!",
     nullptr,
     nullptr,
     0},

    {"enchant armor",
     {16, 60, 60, 60},
     {1, 1, 2, 2},
     spell_enchant_armor,
     TAR_OBJ_INV,
     Position::Type::Standing,
     nullptr,
     SLOT(510),
     100,
     24,
     "",
     "!Enchant Armor!",
     nullptr,
     nullptr,
     0},

    {"protect container",
     {50, 50, 50, 50},
     {1, 1, 2, 2},
     spell_protect_container,
     TAR_OBJ_INV,
     Position::Type::Standing,
     nullptr,
     SLOT(606),
     50,
     24,
     "",
     "!Protect Container!",
     nullptr,
     nullptr,
     0},

    {"venom",
     {60, 60, 60, 10},
     {1, 1, 2, 1},
     spell_venom,
     TAR_OBJ_INV,
     Position::Type::Standing,
     nullptr,
     SLOT(600),
     50,
     24,
     "",
     "!Venom!",
     nullptr,
     nullptr,
     0},

    {"vorpal",
     {93, 93, 93, 93},
     {1, 1, 1, 1},
     spell_vorpal,
     TAR_OBJ_INV,
     Position::Type::Standing,
     nullptr,
     SLOT(608),
     50,
     24,
     "",
     "!Venom!",
     nullptr,
     nullptr,
     0},

    {"vampire",
     {93, 93, 93, 93},
     {1, 1, 2, 1},
     spell_vampire,
     TAR_OBJ_INV,
     Position::Type::Standing,
     nullptr,
     SLOT(605),
     50,
     24,
     "",
     "!Vampire!",
     nullptr,
     nullptr,
     0},

    {"black death",
     {60, 60, 60, 35},
     {2, 2, 2, 1},
     spell_black_death,
     TAR_OBJ_INV,
     Position::Type::Standing,
     nullptr,
     SLOT(601),
     100,
     24,
     "",
     "!Black Death!",
     nullptr,
     nullptr,
     0},

    {"tame lightning",
     {60, 60, 60, 20},
     {2, 2, 2, 1},
     spell_tame_lightning,
     TAR_OBJ_INV,
     Position::Type::Standing,
     nullptr,
     SLOT(602),
     75,
     24,
     "",
     "!Tame Lightning!",
     nullptr,
     nullptr,
     0},

    {"acid wash",
     {60, 60, 60, 45},
     {2, 2, 2, 1},
     spell_acid_wash,
     TAR_OBJ_INV,
     Position::Type::Standing,
     nullptr,
     SLOT(603),
     150,
     24,
     "",
     "!Acid Wash!",
     nullptr,
     nullptr,
     0},

    {"damnation",
     {60, 60, 60, 50},
     {2, 2, 2, 1},
     spell_damnation,
     TAR_OBJ_INV,
     Position::Type::Standing,
     nullptr,
     SLOT(604),
     200,
     24,
     "",
     "!Damnation!",
     nullptr,
     nullptr,
     0},

    {"enchant weapon",
     {17, 60, 60, 60},
     {1, 1, 2, 2},
     spell_enchant_weapon,
     TAR_OBJ_INV,
     Position::Type::Standing,
     nullptr,
     SLOT(24),
     100,
     24,
     "",
     "!Enchant Weapon!",
     nullptr,
     nullptr,
     0},

    {"energy drain",
     {19, 22, 26, 23},
     {1, 1, 2, 2},
     spell_energy_drain,
     TAR_CHAR_OFFENSIVE,
     Position::Type::Fighting,
     nullptr,
     SLOT(25),
     35,
     12,
     "energy drain",
     "!Energy Drain!",
     nullptr,
     nullptr,
     0},

    {"insanity",
     {16, 18, 23, 20},
     {1, 1, 2, 2},
     spell_insanity,
     TAR_CHAR_OFFENSIVE,
     Position::Type::Fighting,
     &gsn_insanity,
     SLOT(206),
     35,
     12,
     "insanity",
     "Your mind clears.",
     check_dispel,
     "$n looks less confused.",
     0},

    {"faerie fire",
     {6, 3, 5, 8},
     {1, 1, 2, 2},
     spell_faerie_fire,
     TAR_CHAR_OFFENSIVE,
     Position::Type::Fighting,
     nullptr,
     SLOT(72),
     5,
     12,
     "faerie fire",
     "The pink aura around you fades away.",
     check_dispel,
     "$n's outline fades.",
     0},

    {"faerie fog",
     {14, 21, 16, 24},
     {1, 1, 2, 2},
     spell_faerie_fog,
     TAR_IGNORE,
     Position::Type::Standing,
     nullptr,
     SLOT(73),
     12,
     12,
     "faerie fog",
     "!Faerie Fog!",
     nullptr,
     nullptr,
     0},

    {"fireball",
     {22, 60, 60, 60},
     {1, 1, 2, 2},
     spell_fireball,
     TAR_CHAR_OFFENSIVE,
     Position::Type::Fighting,
     nullptr,
     SLOT(26),
     15,
     12,
     "fireball",
     "!Fireball!",
     nullptr,
     nullptr,
     0},

    {"flamestrike",
     {60, 20, 27, 60},
     {1, 1, 2, 2},
     spell_flamestrike,
     TAR_CHAR_OFFENSIVE,
     Position::Type::Fighting,
     nullptr,
     SLOT(65),
     20,
     12,
     "flamestrike",
     "!Flamestrike!",
     nullptr,
     nullptr,
     0},

    {"fly",
     {10, 18, 20, 22},
     {1, 1, 2, 2},
     spell_fly,
     TAR_CHAR_DEFENSIVE,
     Position::Type::Standing,
     nullptr,
     SLOT(56),
     10,
     18,
     "",
     "You slowly float to the ground.",
     check_dispel,
     "$n falls to the ground!",
     AFF_FLYING},

    {"frenzy",
     {60, 24, 26, 60},
     {1, 1, 2, 2},
     spell_frenzy,
     TAR_CHAR_DEFENSIVE,
     Position::Type::Standing,
     nullptr,
     SLOT(504),
     30,
     24,
     "",
     "Your rage ebbs.",
     check_dispel,
     "$n no longer looks frenzied.",
     AFF_BERSERK},

    {"gate",
     {27, 17, 28, 28},
     {1, 1, 2, 2},
     spell_gate,
     TAR_IGNORE,
     Position::Type::Fighting,
     nullptr,
     SLOT(83),
     80,
     12,
     "",
     "!Gate!",
     nullptr,
     nullptr,
     0},

    {"giant strength",
     {11, 19, 22, 16},
     {1, 1, 2, 2},
     spell_giant_strength,
     TAR_CHAR_DEFENSIVE,
     Position::Type::Standing,
     nullptr,
     SLOT(39),
     20,
     12,
     "",
     "You feel weaker.",
     check_dispel,
     "$n no longer looks so mighty.",
     0},

    {"harm",
     {60, 23, 26, 60},
     {1, 1, 2, 2},
     spell_harm,
     TAR_CHAR_OFFENSIVE,
     Position::Type::Fighting,
     nullptr,
     SLOT(27),
     35,
     12,
     "harm spell",
     "!Harm!",
     nullptr,
     nullptr,
     0},

    {"haste",
     {21, 29, 27, 26},
     {1, 1, 2, 2},
     spell_haste,
     TAR_CHAR_DEFENSIVE,
     Position::Type::Fighting,
     nullptr,
     SLOT(502),
     30,
     12,
     "",
     "You feel yourself slow down.",
     check_dispel,
     "$n's movements slow down.",
     AFF_HASTE},

    {"regeneration",
     {17, 21, 20, 19},
     {1, 1, 2, 2},
     spell_regeneration,
     TAR_CHAR_DEFENSIVE,
     Position::Type::Standing,
     nullptr,
     SLOT(511),
     12,
     12,
     "You feel vibrant!",
     "You feel less vibrant.",
     check_dispel,
     "The warm glow surrounding $n fades.",
     AFF_REGENERATION},

    {"lethargy",
     {21, 29, 27, 26},
     {1, 1, 2, 2},
     spell_lethargy,
     TAR_CHAR_OFFENSIVE,
     Position::Type::Fighting,
     nullptr,
     SLOT(208),
     30,
     12,
     "",
     "Your heart-beat quickens.",
     check_dispel,
     "$n looks livelier.",
     0},

    {"heal",
     {60, 21, 29, 60},
     {1, 1, 2, 2},
     spell_heal,
     TAR_CHAR_DEFENSIVE,
     Position::Type::Fighting,
     nullptr,
     SLOT(28),
     50,
     12,
     "",
     "!Heal!",
     nullptr,
     nullptr,
     0},

    {"holy word",
     {60, 45, 50, 60},
     {2, 2, 4, 4},
     spell_holy_word,
     TAR_IGNORE,
     Position::Type::Fighting,
     nullptr,
     SLOT(506),
     100,
     24,
     "divine wrath",
     "!Holy Word!",
     nullptr,
     nullptr,
     0},

    {"identify",
     {15, 16, 60, 60},
     {1, 1, 2, 2},
     spell_identify,
     TAR_OBJ_INV,
     Position::Type::Standing,
     nullptr,
     SLOT(53),
     12,
     24,
     "",
     "!Identify!",
     nullptr,
     nullptr,
     0},

    {"infravision",
     {9, 13, 15, 11},
     {1, 1, 2, 2},
     spell_infravision,
     TAR_CHAR_DEFENSIVE,
     Position::Type::Standing,
     nullptr,
     SLOT(77),
     5,
     18,
     "",
     "You no longer see in the dark.",
     check_dispel,
     "$n's eyes stop glowing red.",
     AFF_INFRARED},

    {"invis",
     {5, 60, 60, 60},
     {1, 1, 2, 2},
     spell_invis,
     TAR_CHAR_DEFENSIVE,
     Position::Type::Standing,
     &gsn_invis,
     SLOT(29),
     5,
     12,
     "",
     "You are no longer invisible.",
     check_dispel,
     "$n fades into existence.",
     AFF_INVISIBLE},

    {"know alignment",
     {12, 9, 60, 60},
     {1, 1, 2, 2},
     spell_know_alignment,
     TAR_CHAR_DEFENSIVE,
     Position::Type::Fighting,
     nullptr,
     SLOT(58),
     9,
     12,
     "",
     "!Know Alignment!",
     nullptr,
     nullptr,
     0},

    {"lightning bolt",
     {13, 23, 18, 22},
     {1, 1, 2, 2},
     spell_lightning_bolt,
     TAR_CHAR_OFFENSIVE,
     Position::Type::Fighting,
     nullptr,
     SLOT(30),
     15,
     12,
     "lightning bolt",
     "!Lightning Bolt!",
     nullptr,
     nullptr,
     0},

    {"locate object",
     {9, 15, 60, 60},
     {1, 1, 2, 2},
     spell_locate_object,
     TAR_IGNORE,
     Position::Type::Standing,
     nullptr,
     SLOT(31),
     20,
     18,
     "",
     "!Locate Object!",
     nullptr,
     nullptr,
     0},

    {"magic missile",
     {1, 60, 60, 60},
     {1, 1, 2, 2},
     spell_magic_missile,
     TAR_CHAR_OFFENSIVE,
     Position::Type::Fighting,
     nullptr,
     SLOT(32),
     15,
     12,
     "magic missile",
     "!Magic Missile!",
     nullptr,
     nullptr,
     0},

    {"mass healing",
     {60, 38, 45, 60},
     {2, 2, 4, 4},
     spell_mass_healing,
     TAR_IGNORE,
     Position::Type::Standing,
     nullptr,
     SLOT(508),
     100,
     36,
     "",
     "!Mass Healing!",
     nullptr,
     nullptr,
     0},

    {"mass invis",
     {22, 60, 60, 60},
     {1, 1, 2, 2},
     spell_mass_invis,
     TAR_IGNORE,
     Position::Type::Standing,
     &gsn_mass_invis,
     SLOT(69),
     20,
     24,
     "",
     "You are no longer invisible.",
     check_dispel,
     "$n fades into existence.",
     0},

    {"pass door",
     {24, 30, 28, 34},
     {1, 1, 2, 2},
     spell_pass_door,
     TAR_CHAR_DEFENSIVE,
     Position::Type::Standing,
     nullptr,
     SLOT(74),
     20,
     12,
     "",
     "You feel solid again.",
     check_dispel,
     "$n drifts back into phase.",
     AFF_PASS_DOOR},

    {"plague",
     {23, 17, 36, 26},
     {1, 1, 2, 2},
     spell_plague,
     TAR_CHAR_OFFENSIVE,
     Position::Type::Fighting,
     &gsn_plague,
     SLOT(503),
     20,
     12,
     "sickness",
     "Your sores vanish.",
     nullptr,
     nullptr,
     0},

    {"poison",
     {17, 12, 15, 21},
     {1, 1, 2, 2},
     spell_poison,
     TAR_CHAR_OFFENSIVE,
     Position::Type::Fighting,
     &gsn_poison,
     SLOT(33),
     10,
     12,
     "poison",
     "You feel less sick.",
     nullptr,
     nullptr,
     0},

    {"portal",
     {40, 40, 40, 40},
     {1, 1, 2, 2},
     spell_portal,
     TAR_IGNORE,
     Position::Type::Standing,
     nullptr,
     SLOT(516),
     100,
     12,
     "",
     "",
     nullptr,
     nullptr,
     0},

    {"protection evil",
     {12, 9, 12, 12},
     {1, 1, 2, 2},
     spell_protection_evil,
     TAR_CHAR_SELF,
     Position::Type::Standing,
     nullptr,
     SLOT(34),
     5,
     12,
     "",
     "You feel less protected from evil.",
     check_dispel,
     "$n looks less protected from the forces of evil.",
     AFF_PROTECTION_EVIL},

    {"protection good",
     {12, 9, 12, 12},
     {1, 1, 2, 2},
     spell_protection_good,
     TAR_CHAR_SELF,
     Position::Type::Standing,
     nullptr,
     SLOT(607),
     5,
     12,
     "",
     "You feel less protected from good.",
     check_dispel,
     "$n looks less protected from the powers of good.",
     AFF_PROTECTION_GOOD},

    {"psychic tornado",
     {60, 50, 70, 70},
     {1, 1, 2, 2},
     spell_psy_tornado,
     TAR_CHAR_OFFENSIVE,
     Position::Type::Standing,
     nullptr,
     SLOT(207),
     100,
     16,
     "psychic tornado",
     "You regain your senses.",
     nullptr,
     nullptr,
     0},

    {"refresh",
     {8, 5, 12, 9},
     {1, 1, 2, 2},
     spell_refresh,
     TAR_CHAR_DEFENSIVE,
     Position::Type::Standing,
     nullptr,
     SLOT(81),
     12,
     18,
     "refresh",
     "!Refresh!",
     nullptr,
     nullptr,
     0},

    {"remove curse",
     {60, 18, 40, 60},
     {1, 1, 2, 2},
     spell_remove_curse,
     TAR_CHAR_DEFENSIVE,
     Position::Type::Standing,
     nullptr,
     SLOT(35),
     5,
     12,
     "",
     "!Remove Curse!",
     nullptr,
     nullptr,
     0},

    {"remove alignment",
     {60, 18, 60, 60},
     {1, 1, 2, 2},
     spell_remove_alignment,
     TAR_OBJ_INV,
     Position::Type::Standing,
     nullptr,
     SLOT(512),
     100,
     12,
     "",
     "!Remove Alignment!",
     nullptr,
     nullptr,
     0},

    {"remove invisible",
     {60, 18, 60, 60},
     {1, 1, 2, 2},
     spell_remove_invisible,
     TAR_OBJ_INV,
     Position::Type::Standing,
     nullptr,
     SLOT(513),
     30,
     12,
     "",
     "!Remove Invisible!",
     nullptr,
     nullptr,
     0},

    {"talon",
     {40, 40, 40, 40},
     {1, 1, 2, 2},
     spell_talon,
     TAR_CHAR_DEFENSIVE,
     Position::Type::Standing,
     nullptr,
     SLOT(37),
     28,
     12,
     "",
     "Your hands return to normal.",
     check_dispel,
     "$n's hands return to normal.",
     AFF_TALON},

    {"sanctuary",
     {36, 20, 30, 37},
     {1, 1, 2, 2},
     spell_sanctuary,
     TAR_CHAR_DEFENSIVE,
     Position::Type::Standing,
     nullptr,
     SLOT(36),
     75,
     12,
     "",
     "The white aura around your body fades.",
     check_dispel,
     "The white aura around $n's body vanishes.",
     AFF_SANCTUARY},

    {"shield",
     {20, 35, 35, 34},
     {1, 1, 2, 2},
     spell_shield,
     TAR_CHAR_DEFENSIVE,
     Position::Type::Standing,
     nullptr,
     SLOT(67),
     12,
     18,
     "",
     "Your force shield shimmers then fades away.",
     check_dispel,
     "The force shield protecting $n vanishes",
     0},

    {"shocking grasp",
     {10, 60, 60, 60},
     {1, 1, 2, 2},
     spell_shocking_grasp,
     TAR_CHAR_OFFENSIVE,
     Position::Type::Fighting,
     nullptr,
     SLOT(53),
     15,
     12,
     "shocking grasp",
     "!Shocking Grasp!",
     nullptr,
     nullptr,
     0},

    {"sleep",
     {10, 60, 60, 60},
     {1, 1, 2, 2},
     spell_sleep,
     TAR_CHAR_OFFENSIVE,
     Position::Type::Standing,
     &gsn_sleep,
     SLOT(38),
     15,
     12,
     "",
     "You feel less tired.",
     check_dispel,
     "$n looks less sleepy.",
     0},

    {"stone skin",
     {25, 40, 40, 45},
     {1, 1, 2, 2},
     spell_stone_skin,
     TAR_CHAR_SELF,
     Position::Type::Standing,
     nullptr,
     SLOT(66),
     12,
     18,
     "",
     "Your skin feels soft again.",
     check_dispel,
     "$n's skin regains its normal texture.",
     0},

    {"summon",
     {24, 12, 29, 30},
     {1, 1, 2, 2},
     spell_summon,
     TAR_IGNORE,
     Position::Type::Standing,
     nullptr,
     SLOT(40),
     50,
     12,
     "",
     "!Summon!",
     nullptr,
     nullptr,
     0},

    {"teleport",
     {13, 22, 25, 36},
     {1, 1, 2, 2},
     spell_teleport,
     TAR_CHAR_SELF,
     Position::Type::Fighting,
     nullptr,
     SLOT(2),
     35,
     12,
     "",
     "!Teleport!",
     nullptr,
     nullptr,
     0},

    {"teleport object",
     {60, 60, 60, 60},
     {1, 1, 2, 2},
     spell_teleport_object,
     TAR_CHAR_OTHER,
     Position::Type::Standing,
     nullptr,
     SLOT(205),
     35,
     12,
     "",
     "!Teleport Object!",
     nullptr,
     nullptr,
     0},

    {"undo spell",
     {60, 60, 60, 60},
     {1, 1, 2, 2},
     spell_undo_spell,
     TAR_CHAR_OTHER,
     Position::Type::Fighting,
     nullptr,
     SLOT(199),
     12,
     12,
     "",
     "!Undo Spell!",
     nullptr,
     nullptr,
     0},

    {"ventriloquate",
     {1, 60, 60, 60},
     {1, 1, 2, 2},
     spell_ventriloquate,
     TAR_IGNORE,
     Position::Type::Standing,
     nullptr,
     SLOT(41),
     5,
     12,
     "",
     "!Ventriloquate!",
     nullptr,
     nullptr,
     0},

    {"weaken",
     {11, 14, 16, 17},
     {1, 1, 2, 2},
     spell_weaken,
     TAR_CHAR_OFFENSIVE,
     Position::Type::Fighting,
     nullptr,
     SLOT(68),
     20,
     12,
     "spell",
     "You feel stronger.",
     check_dispel,
     "$n looks stronger.",
     0},

    {"word of recall",
     {32, 28, 32, 33},
     {1, 1, 2, 2},
     spell_word_of_recall,
     TAR_CHAR_SELF,
     Position::Type::Resting,
     nullptr,
     SLOT(42),
     5,
     12,
     "",
     "!Word of Recall!",
     nullptr,
     nullptr,
     0},

    /*
     * Dragon breath
     */
    {"acid breath",
     {42, 44, 46, 48},
     {1, 1, 2, 2},
     spell_acid_breath,
     TAR_CHAR_OFFENSIVE,
     Position::Type::Fighting,
     nullptr,
     SLOT(200),
     12,
     12,
     "blast of acid",
     "!Acid Breath!",
     nullptr,
     nullptr,
     0},

    {"fire breath",
     {38, 40, 42, 44},
     {1, 1, 2, 2},
     spell_fire_breath,
     TAR_CHAR_OFFENSIVE,
     Position::Type::Fighting,
     nullptr,
     SLOT(201),
     12,
     12,
     "blast of flame",
     "!Fire Breath!",
     nullptr,
     nullptr,
     0},

    {"frost breath",
     {30, 32, 34, 36},
     {1, 1, 2, 2},
     spell_frost_breath,
     TAR_CHAR_OFFENSIVE,
     Position::Type::Fighting,
     nullptr,
     SLOT(202),
     12,
     12,
     "blast of frost",
     "!Frost Breath!",
     nullptr,
     nullptr,
     0},

    {"gas breath",
     {46, 48, 50, 52},
     {1, 1, 2, 2},
     spell_gas_breath,
     TAR_IGNORE,
     Position::Type::Fighting,
     nullptr,
     SLOT(203),
     12,
     12,
     "blast of gas",
     "!Gas Breath!",
     nullptr,
     nullptr,
     0},

    {"lightning breath",
     {34, 36, 38, 40},
     {1, 1, 2, 2},
     spell_lightning_breath,
     TAR_CHAR_OFFENSIVE,
     Position::Type::Fighting,
     nullptr,
     SLOT(204),
     12,
     12,
     "blast of lightning",
     "!Lightning Breath!",
     nullptr,
     nullptr,
     0},

    /*
     * Spells for mega1.are from Glop/Erkenbrand.
     */
    {"general purpose",
     {53, 53, 53, 53},
     {0, 0, 0, 0},
     spell_general_purpose,
     TAR_CHAR_OFFENSIVE,
     Position::Type::Fighting,
     nullptr,
     SLOT(401),
     0,
     12,
     "general purpose ammo",
     "!General Purpose Ammo!",
     nullptr,
     nullptr,
     0},

    {"high explosive",
     {53, 53, 53, 53},
     {0, 0, 0, 0},
     spell_high_explosive,
     TAR_CHAR_OFFENSIVE,
     Position::Type::Fighting,
     nullptr,
     SLOT(402),
     0,
     12,
     "high explosive ammo",
     "!High Explosive Ammo!",
     nullptr,
     nullptr,
     0},

    /* combat and weapons skills */

    {"axe",
     {1, 1, 1, 1},
     {6, 6, 4, 2},
     spell_null,
     TAR_IGNORE,
     Position::Type::Fighting,
     &gsn_axe,
     SLOT(0),
     0,
     0,
     "",
     "!Axe!",
     nullptr,
     nullptr,
     0},

    {"dagger",
     {1, 1, 1, 1},
     {2, 3, 2, 3},
     spell_null,
     TAR_IGNORE,
     Position::Type::Fighting,
     &gsn_dagger,
     SLOT(0),
     0,
     0,
     "",
     "!Dagger!",
     nullptr,
     nullptr,
     0},

    {"flail",
     {1, 1, 1, 1},
     {6, 3, 4, 5},
     spell_null,
     TAR_IGNORE,
     Position::Type::Fighting,
     &gsn_flail,
     SLOT(0),
     0,
     0,
     "",
     "!Flail!",
     nullptr,
     nullptr,
     0},

    {"mace",
     {1, 1, 1, 1},
     {5, 2, 3, 3},
     spell_null,
     TAR_IGNORE,
     Position::Type::Fighting,
     &gsn_mace,
     SLOT(0),
     0,
     0,
     "",
     "!Mace!",
     nullptr,
     nullptr,
     0},

    {"polearm",
     {1, 1, 1, 1},
     {6, 6, 4, 6},
     spell_null,
     TAR_IGNORE,
     Position::Type::Fighting,
     &gsn_polearm,
     SLOT(0),
     0,
     0,
     "",
     "!Polearm!",
     nullptr,
     nullptr,
     0},

    {"shield block",
     {1, 1, 1, 1},
     {6, 4, 3, 2},
     spell_null,
     TAR_IGNORE,
     Position::Type::Fighting,
     &gsn_shield_block,
     SLOT(0),
     0,
     0,
     "",
     "!Shield!",
     nullptr,
     nullptr,
     0},

    {"spear",
     {1, 1, 1, 1},
     {4, 4, 4, 3},
     spell_null,
     TAR_IGNORE,
     Position::Type::Fighting,
     &gsn_spear,
     SLOT(0),
     0,
     0,
     "",
     "!Spear!",
     nullptr,
     nullptr,
     0},

    {"sword",
     {1, 1, 1, 1},
     {8, 6, 2, 4},
     spell_null,
     TAR_IGNORE,
     Position::Type::Fighting,
     &gsn_sword,
     SLOT(0),
     0,
     0,
     "",
     "!sword!",
     nullptr,
     nullptr,
     0},

    {"whip",
     {1, 1, 1, 1},
     {6, 5, 5, 4},
     spell_null,
     TAR_IGNORE,
     Position::Type::Fighting,
     &gsn_whip,
     SLOT(0),
     0,
     0,
     "",
     "!Whip!",
     nullptr,
     nullptr,
     0},

    {"backstab",
     {30, 30, 30, 30},
     {SKILL_ASSASSIN, SKILL_ASSASSIN, SKILL_ASSASSIN, SKILL_ASSASSIN},
     spell_null,
     TAR_IGNORE,
     Position::Type::Standing,
     &gsn_backstab,
     SLOT(0),
     0,
     24,
     "backstab",
     "!Backstab!",
     nullptr,
     nullptr,
     0},

    {"bash",
     {60, 60, 5, 1},
     {SKILL_ATTAINABLE, SKILL_ATTAINABLE, 3, 2},
     spell_null,
     TAR_IGNORE,
     Position::Type::Fighting,
     &gsn_bash,
     SLOT(0),
     0,
     24,
     "bash",
     "!Bash!",
     nullptr,
     nullptr,
     0},

    {"berserk",
     {60, 60, 25, 15},
     {SKILL_ATTAINABLE, SKILL_ATTAINABLE, 6, 4},
     spell_null,
     TAR_IGNORE,
     Position::Type::Fighting,
     &gsn_berserk,
     SLOT(0),
     0,
     24,
     "",
     "You feel your pulse slow down.",
     nullptr,
     nullptr,
     0},

    {"dirt kicking",
     {60, 60, 6, 3},
     {SKILL_ATTAINABLE, SKILL_ATTAINABLE, 5, 4},
     spell_null,
     TAR_IGNORE,
     Position::Type::Fighting,
     &gsn_dirt,
     SLOT(0),
     0,
     24,
     "kicked dirt",
     "You rub the dirt out of your eyes.",
     nullptr,
     nullptr,
     0},

    {"disarm",
     {60, 60, 6, 11},
     {SKILL_ATTAINABLE, SKILL_ATTAINABLE, 4, 6},
     spell_null,
     TAR_IGNORE,
     Position::Type::Fighting,
     &gsn_disarm,
     SLOT(0),
     0,
     24,
     "",
     "!Disarm!",
     nullptr,
     nullptr,
     0},

    {"dodge",
     {20, 22, 5, 1},
     {8, 8, 8, 6},
     spell_null,
     TAR_IGNORE,
     Position::Type::Fighting,
     &gsn_dodge,
     SLOT(0),
     0,
     0,
     "",
     "!Dodge!",
     nullptr,
     nullptr,
     0},

    {"enhanced damage",
     {60, 60, 5, 1},
     {SKILL_ATTAINABLE, 9, 5, 3},
     spell_null,
     TAR_IGNORE,
     Position::Type::Fighting,
     &gsn_enhanced_damage,
     SLOT(0),
     0,
     0,
     "",
     "!Enhanced Damage!",
     nullptr,
     nullptr,
     0},

    {"hand to hand",
     {25, 10, 10, 6},
     {8, 5, 4, 3},
     spell_null,
     TAR_IGNORE,
     Position::Type::Fighting,
     &gsn_hand_to_hand,
     SLOT(0),
     0,
     0,
     "",
     "!Hand to Hand!",
     nullptr,
     nullptr,
     0},

    {"kick",
     {60, 12, 12, 8},
     {SKILL_ATTAINABLE, 4, 4, 3},
     spell_null,
     TAR_CHAR_OFFENSIVE,
     Position::Type::Fighting,
     &gsn_kick,
     SLOT(0),
     0,
     12,
     "kick",
     "!Kick!",
     nullptr,
     nullptr,
     0},

    {"headbutt",
     {60, 60, 20, 5},
     {SKILL_ATTAINABLE, SKILL_ATTAINABLE, 8, 3},
     spell_null,
     TAR_CHAR_OFFENSIVE,
     Position::Type::Fighting,
     &gsn_headbutt,
     SLOT(0),
     0,
     12,
     "headbutt",
     "You wipe the blood from your eyes.",
     nullptr,
     nullptr,
     0},

    {"parry",
     {22, 20, 1, 5},
     {8, 8, 4, 5},
     spell_null,
     TAR_IGNORE,
     Position::Type::Fighting,
     &gsn_parry,
     SLOT(0),
     0,
     0,
     "",
     "!Parry!",
     nullptr,
     nullptr,
     0},

    {"rescue",
     {60, 60, 3, 1},
     {SKILL_ATTAINABLE, 6, 2, 4},
     spell_null,
     TAR_IGNORE,
     Position::Type::Fighting,
     &gsn_rescue,
     SLOT(0),
     0,
     12,
     "",
     "!Rescue!",
     nullptr,
     nullptr,
     0},

    {"trip",
     {60, 60, 1, 1},
     {SKILL_ATTAINABLE, SKILL_ATTAINABLE, 4, 3},
     spell_null,
     TAR_IGNORE,
     Position::Type::Fighting,
     &gsn_trip,
     SLOT(0),
     0,
     24,
     "trip",
     "!Trip!",
     nullptr,
     nullptr,
     0},

    {"second attack",
     {30, 24, 7, 5},
     {10, 8, 4, 3},
     spell_null,
     TAR_IGNORE,
     Position::Type::Fighting,
     &gsn_second_attack,
     SLOT(0),
     0,
     0,
     "",
     "!Second Attack!",
     nullptr,
     nullptr,
     0},

    {"third attack",
     {60, 60, 14, 12},
     {SKILL_ATTAINABLE, SKILL_ATTAINABLE, 6, 4},
     spell_null,
     TAR_IGNORE,
     Position::Type::Fighting,
     &gsn_third_attack,
     SLOT(0),
     0,
     0,
     "",
     "!Third Attack!",
     nullptr,
     nullptr,
     0},

    /* non-combat skills */

    {"fast healing",
     {15, 9, 8, 6},
     {8, 5, 4, 3},
     spell_null,
     TAR_IGNORE,
     Position::Type::Sleeping,
     &gsn_fast_healing,
     SLOT(0),
     0,
     0,
     "",
     "!Fast Healing!",
     nullptr,
     nullptr,
     0},

    {"haggle",
     {7, 18, 10, 14},
     {5, 8, 6, 6},
     spell_null,
     TAR_IGNORE,
     Position::Type::Resting,
     &gsn_haggle,
     SLOT(0),
     0,
     0,
     "",
     "!Haggle!",
     nullptr,
     nullptr,
     0},

    {"hide",
     {30, 30, 30, 30},
     {SKILL_ASSASSIN, SKILL_ASSASSIN, SKILL_ASSASSIN, SKILL_ASSASSIN},
     spell_null,
     TAR_IGNORE,
     Position::Type::Resting,
     &gsn_hide,
     SLOT(0),
     0,
     12,
     "",
     "!Hide!",
     nullptr,
     nullptr,
     0},

    {"lore",
     {10, 10, 16, 20},
     {6, 6, 8, 8},
     spell_null,
     TAR_IGNORE,
     Position::Type::Resting,
     &gsn_lore,
     SLOT(0),
     0,
     36,
     "",
     "!Lore!",
     nullptr,
     nullptr,
     0},

    {"meditation",
     {6, 6, 15, 15},
     {5, 5, 8, 8},
     spell_null,
     TAR_IGNORE,
     Position::Type::Sleeping,
     &gsn_meditation,
     SLOT(0),
     0,
     0,
     "",
     "Meditation",
     nullptr,
     nullptr,
     0},

    {"peek",
     {30, 30, 30, 30},
     {SKILL_ASSASSIN, SKILL_ASSASSIN, SKILL_ASSASSIN, SKILL_ASSASSIN},
     spell_null,
     TAR_IGNORE,
     Position::Type::Standing,
     &gsn_peek,
     SLOT(0),
     0,
     0,
     "",
     "!Peek!",
     nullptr,
     nullptr,
     0},

    {"ride",
     {60, 60, 5, 60},
     {SKILL_ATTAINABLE, SKILL_ATTAINABLE, 4, SKILL_ATTAINABLE},
     spell_null,
     TAR_IGNORE,
     Position::Type::Standing,
     &gsn_ride,
     SLOT(0),
     0,
     0,
     "",
     "!Ride!",
     nullptr,
     nullptr,
     0},

    {"sharpen",
     {60, 60, 15, 60},
     {SKILL_ATTAINABLE, SKILL_ATTAINABLE, 4, SKILL_ATTAINABLE},
     spell_null,
     TAR_OBJ_INV,
     Position::Type::Standing,
     &gsn_sharpen,
     SLOT(0),
     0,
     0,
     "",
     "!Sharpen!",
     nullptr,
     nullptr,
     0},

    {"pick lock",
     {25, 25, 25, 25},
     {5, 5, 5, 5},
     spell_null,
     TAR_IGNORE,
     Position::Type::Standing,
     &gsn_pick_lock,
     SLOT(0),
     0,
     12,
     "",
     "!Pick!",
     nullptr,
     nullptr,
     0},

    {"sneak",
     {30, 30, 30, 30},
     {SKILL_ASSASSIN, SKILL_ASSASSIN, SKILL_ASSASSIN, SKILL_ASSASSIN},
     spell_null,
     TAR_IGNORE,
     Position::Type::Standing,
     &gsn_sneak,
     SLOT(0),
     0,
     12,
     "",
     "You no longer feel stealthy.",
     nullptr,
     nullptr,
     0},

    {"steal",
     {30, 30, 30, 30},
     {SKILL_ASSASSIN, SKILL_ASSASSIN, SKILL_ASSASSIN, SKILL_ASSASSIN},
     spell_null,
     TAR_IGNORE,
     Position::Type::Standing,
     &gsn_steal,
     SLOT(0),
     0,
     24,
     "",
     "!Steal!",
     nullptr,
     nullptr,
     0},

    {"scrolls",
     {1, 1, 1, 1},
     {2, 3, 6, 8},
     spell_null,
     TAR_IGNORE,
     Position::Type::Standing,
     &gsn_scrolls,
     SLOT(0),
     0,
     24,
     "",
     "!Scrolls!",
     nullptr,
     nullptr,
     0},

    {"staves",
     {1, 1, 1, 1},
     {2, 3, 6, 8},
     spell_null,
     TAR_IGNORE,
     Position::Type::Standing,
     &gsn_staves,
     SLOT(0),
     0,
     12,
     "",
     "!Staves!",
     nullptr,
     nullptr,
     0},

    {"wands",
     {1, 1, 1, 1},
     {2, 3, 6, 8},
     spell_null,
     TAR_IGNORE,
     Position::Type::Standing,
     &gsn_wands,
     SLOT(0),
     0,
     12,
     "",
     "!Wands!",
     nullptr,
     nullptr,
     0},

    {"throw",
     {15, 15, 15, 15},
     {2, 2, 3, 5},
     spell_null,
     TAR_IGNORE,
     Position::Type::Standing,
     &gsn_throw,
     SLOT(0),
     0,
     12,
     "",
     "!Throw!",
     nullptr,
     nullptr,
     0},

    {"recall",
     {1, 1, 1, 1},
     {2, 2, 2, 2},
     spell_null,
     TAR_IGNORE,
     Position::Type::Standing,
     &gsn_recall,
     SLOT(0),
     0,
     12,
     "",
     "!Recall!",
     nullptr,
     nullptr,
     0}

    /* commented out for time being --Fara
      {
       "raise dead",      {
          1,  1,  1,  1       }
       ,  {
         SKILL_ATTAINABLE, SKILL_ATTAINABLE,
         SKILL_ATTAINABLE, SKILL_ATTAINABLE }
       ,
       spell_raise_dead,    TAR_IGNORE,    Position::Type::Standing,
       &gsn_raise_dead,      SLOT( 209),   100, 12,
       "",         "!Raise dead!",      nullptr, nullptr, 0
       }, */

};

const struct group_type group_table[MAX_GROUP] = {

    {"rom basics", {0, 0, 0, 0}, {"scrolls", "staves", "wands", "recall", "throw"}},

    {"mage basics", {0, -3, -3, -3}, {"dagger"}},

    {"cleric basics", {-3, 0, -3, -3}, {"mace"}},

    {"knight basics", {-3, -3, 0, -3}, {"sword", "ride"}},

    {"barbarian basics", {-3, -3, -3, 0}, {"axe", "enhanced damage"}},

    {"mage default",
     {40, -3, -3, -3},
     {"lore", "beguiling", "combat", "detection", "enhancement", "illusion", "maledictions", "protective",
      "transportation", "weather"}},

    {"cleric default",
     {-3, 40, -3, -3},
     {"flail", "attack", "creation", "curative", "benedictions", "detection", "healing", "maledictions", "protective",
      "shield block", "transportation", "weather"}},

    {"knight default",
     {-3, -3, 40, -3},
     {"second attack", "shield block", "parry", "rescue", "disarm", "weaponsmaster", "bash"}},

    {"barbarian default",
     {-3, -3, -3, 40},
     {"shield block", "dodge", "berserk", "dirt kick", "second attack", "third attack", "kick", "hand to hand", "trip",
      "weapon craft"}},

    {"assassin", {20, 20, 20, 20}, {"sneak", "hide", "backstab", "steal", "peek", "dagger"}},

    {"weaponsmaster", {40, 35, 20, 25}, {"axe", "dagger", "flail", "mace", "polearm", "spear", "sword", "whip"}},

    {"attack", {-1, 5, 8, -1}, {"demonfire", "dispel evil", "dispel good", "earthquake", "flamestrike", "exorcise"}},

    {"weapon craft", {-1, -1, -1, 8}, {"venom", "tame lightning", "black death", "acid wash", "damnation"}},

    {"beguiling", {4, -1, -1, -1}, {"charm person", "sleep"}},

    {"benedictions",
     {-1, 4, 8, -1},
     {"bless", "calm", "frenzy", "holy word", "remove curse", "remove invisible", "remove alignment"}},

    {"combat",
     {6, -1, -1, -1},
     {"acid blast", "burning hands", "chain lightning", "chill touch", "colour spray", "fireball", "lightning bolt",
      "magic missile", "shocking grasp"}},

    {"creation", {4, 4, 8, 8}, {"continual light", "create food", "create spring", "create water"}},

    {"curative", {-1, 4, 6, 8}, {"cure blindness", "cure disease", "cure poison"}},

    {"detection",
     {4, 3, -1, -1},
     {"detect evil", "detect hidden", "detect invis", "detect magic", "detect poison", "identify", "know alignment",
      "locate object"}},

    {"draconian", {8, -1, -1, -1}, {"acid breath", "fire breath", "frost breath", "gas breath", "lightning breath"}},

    {"enchantment", {6, -1, -1, -1}, {"enchant armor", "enchant weapon"}},

    {"enhancement", {5, -1, 9, 10}, {"giant strength", "haste", "infravision", "refresh", "regeneration"}},

    {"harmful", {-1, 3, 6, -1}, {"cause critical", "cause light", "cause serious", "harm"}},

    {"healing", {-1, 3, 6, -1}, {"cure critical", "cure light", "cure serious", "heal", "mass healing", "refresh"}},

    {"illusion", {4, -1, -1, -1}, {"invis", "mass invis", "ventriloquate"}},

    {"maledictions",
     {5, 5, 8, 10},
     {"blindness", "change sex", "curse", "energy drain", "plague", "poison", "weaken", "lethargy", "insanity"}},

    {"protective",
     {4, 4, 8, 10},
     {"armor", "cancellation", "dispel magic", "protection evil", "sanctuary", "shield", "stone skin",
      "protection good"}},

    {"specialities", {10, 10, 10, 10}, {"teleport object", "undo spell", "protect container", "talon"}},

    {"transportation", {4, 4, 8, 10}, {"fly", "gate", "pass door", "summon", "teleport", "word of recall", "portal"}},

    {"weather",
     {4, 4, 8, 8},
     {"call lightning", "control weather", "faerie fire", "faerie fog", "lightning bolt", "octarine fire",
      "psychic tornado"}}

};
