/*************************************************************************/
/*  Xania (M)ulti(U)ser(D)ungeon server source code                      */
/*  (C) 2021 Xania Development Team                                      */
/*  See merc.h and README for original copyrights                        */
/*************************************************************************/
#include "SkillTables.hpp"
#include "SkillNumbers.hpp"
#include "magic.h"
#include "merc.h"

/*
 * The skill and spell table.
 * Slot numbers must never be changed as they appear in #OBJECTS sections.
 */
#define SLOT(n) n

const struct skill_type skill_table[MAX_SKILL] = {

    /*
     * Magic spells.
     */

    {
        "reserved",
        0,
        nullptr,
        "",
        "",
        nullptr,
        nullptr,
        0,
        TAR_IGNORE,
        Position::Type::Standing,
        SLOT(0),
        0,
        0,
        {99, 99, 99, 99},
        {99, 99, 99, 99},
    },

    {
        "acid blast",
        spell_acid_blast,
        nullptr,
        "acid blast",
        "!Acid Blast!",
        nullptr,
        nullptr,
        0,
        TAR_CHAR_OFFENSIVE,
        Position::Type::Fighting,
        SLOT(70),
        20,
        12,
        {28, 60, 60, 60},
        {1, 1, 2, 2},
    },

    {
        "octarine fire",
        spell_octarine_fire,
        &gsn_octarine_fire,
        "octarine fire",
        "The octarine fire earths to the ground.",
        check_dispel,
        "$n's octarine outline discharges into the ground.",
        0,
        TAR_CHAR_OFFENSIVE,
        Position::Type::Fighting,
        SLOT(99),
        50,
        12,
        {40, 60, 60, 60},
        {2, 3, 3, 3},
    },

    {
        "armor",
        spell_armor,
        nullptr,
        "",
        "You feel less protected.",
        check_dispel,
        "$n is no longer protected.",
        0,
        TAR_CHAR_DEFENSIVE,
        Position::Type::Standing,
        SLOT(1),
        5,
        12,
        {7, 2, 3, 5},
        {1, 1, 2, 2},
    },

    {
        "bless",
        spell_bless,
        &gsn_bless,
        "",
        "You feel less righteous.",
        check_dispel,
        "$n no longer has divine favour.",
        0,
        TAR_CHAR_DEFENSIVE,
        Position::Type::Standing,
        SLOT(3),
        5,
        12,
        {60, 7, 9, 60},
        {1, 1, 2, 2},
    },

    {
        "blindness",
        spell_blindness,
        &gsn_blindness,
        "",
        "You can see again.",
        check_dispel,
        "$n can see again.",
        AFF_BLIND,
        TAR_CHAR_OFFENSIVE,
        Position::Type::Fighting,
        SLOT(4),
        5,
        12,
        {12, 8, 11, 15},
        {1, 1, 2, 2},
    },

    {
        "burning hands",
        spell_burning_hands,
        nullptr,
        "burning hands",
        "!Burning Hands!",
        nullptr,
        nullptr,
        0,
        TAR_CHAR_OFFENSIVE,
        Position::Type::Fighting,
        SLOT(5),
        15,
        12,
        {7, 60, 60, 60},
        {1, 1, 2, 2},
    },

    {
        "call lightning",
        spell_call_lightning,
        nullptr,
        "lightning bolt",
        "!Call Lightning!",
        nullptr,
        nullptr,
        0,
        TAR_IGNORE,
        Position::Type::Fighting,
        SLOT(6),
        15,
        12,
        {26, 18, 22, 29},
        {1, 1, 2, 2},
    },

    {
        "calm",
        spell_calm,
        nullptr,
        "",
        "You have lost your peace of mind.",
        check_dispel,
        "$n no longer looks so peaceful.",
        AFF_CALM,
        TAR_IGNORE,
        Position::Type::Fighting,
        SLOT(509),
        30,
        12,
        {60, 16, 20, 60},
        {1, 1, 2, 2},
    },

    {
        "cancellation",
        spell_cancellation,
        nullptr,
        "",
        "!cancellation!",
        nullptr,
        nullptr,
        0,
        TAR_CHAR_DEFENSIVE,
        Position::Type::Fighting,
        SLOT(507),
        20,
        12,
        {18, 26, 34, 34},
        {1, 1, 2, 2},
    },

    {
        "cause critical",
        spell_cause_critical,
        nullptr,
        "spell",
        "!Cause Critical!",
        nullptr,
        nullptr,
        0,
        TAR_CHAR_OFFENSIVE,
        Position::Type::Fighting,
        SLOT(63),
        20,
        12,
        {60, 13, 19, 60},
        {1, 1, 2, 2},
    },

    {
        "cause light",
        spell_cause_light,
        nullptr,
        "spell",
        "!Cause Light!",
        nullptr,
        nullptr,
        0,
        TAR_CHAR_OFFENSIVE,
        Position::Type::Fighting,
        SLOT(62),
        15,
        12,
        {60, 1, 3, 60},
        {1, 1, 2, 2},
    },

    {
        "cause serious",
        spell_cause_serious,
        nullptr,
        "spell",
        "!Cause Serious!",
        nullptr,
        nullptr,
        0,
        TAR_CHAR_OFFENSIVE,
        Position::Type::Fighting,
        SLOT(64),
        17,
        12,
        {60, 7, 10, 60},
        {1, 1, 2, 2},
    },

    {
        "chain lightning",
        spell_chain_lightning,
        nullptr,
        "lightning",
        "!Chain Lightning!",
        nullptr,
        nullptr,
        0,
        TAR_CHAR_OFFENSIVE,
        Position::Type::Fighting,
        SLOT(500),
        45,
        14,
        {33, 60, 60, 60},
        {1, 1, 2, 2},
    },

    {
        "change sex",
        spell_change_sex,
        nullptr,
        "",
        "Your body feels familiar again.",
        check_dispel,
        "$n looks more like $r again.",
        0,
        TAR_CHAR_DEFENSIVE,
        Position::Type::Fighting,
        SLOT(82),
        15,
        12,
        {60, 60, 60, 60},
        {1, 1, 2, 2},
    },

    {
        "charm person",
        spell_charm_person,
        &gsn_charm_person,
        "",
        "You feel more self-confident.",
        check_dispel,
        "$n regains $s free will.",
        0,
        TAR_CHAR_OFFENSIVE,
        Position::Type::Standing,
        SLOT(7),
        5,
        12,
        {20, 60, 25, 60},
        {1, 1, 2, 2},
    },

    {
        "chill touch",
        spell_chill_touch,
        nullptr,
        "chilling touch",
        "You feel less cold.",
        check_dispel,
        "$n looks warmer.",
        0,
        TAR_CHAR_OFFENSIVE,
        Position::Type::Fighting,
        SLOT(8),
        15,
        12,
        {4, 60, 60, 60},
        {1, 1, 2, 2},
    },

    {
        "colour spray",
        spell_colour_spray,
        nullptr,
        "colour spray",
        "!Colour Spray!",
        nullptr,
        nullptr,
        0,
        TAR_CHAR_OFFENSIVE,
        Position::Type::Fighting,
        SLOT(10),
        15,
        12,
        {16, 60, 60, 60},
        {1, 1, 2, 2},
    },

    {
        "continual light",
        spell_continual_light,
        nullptr,
        "",
        "!Continual Light!",
        nullptr,
        nullptr,
        0,
        TAR_IGNORE,
        Position::Type::Standing,
        SLOT(57),
        7,
        12,
        {6, 4, 6, 9},
        {1, 1, 2, 2},
    },

    {
        "control weather",
        spell_control_weather,
        nullptr,
        "",
        "!Control Weather!",
        nullptr,
        nullptr,
        0,
        TAR_IGNORE,
        Position::Type::Standing,
        SLOT(11),
        25,
        12,
        {15, 19, 22, 28},
        {1, 1, 2, 2},
    },

    {
        "create food",
        spell_create_food,
        nullptr,
        "",
        "!Create Food!",
        nullptr,
        nullptr,
        0,
        TAR_IGNORE,
        Position::Type::Standing,
        SLOT(12),
        5,
        12,
        {10, 5, 11, 11},
        {1, 1, 2, 2},
    },

    {
        "create spring",
        spell_create_spring,
        nullptr,
        "",
        "!Create Spring!",
        nullptr,
        nullptr,
        0,
        TAR_IGNORE,
        Position::Type::Standing,
        SLOT(80),
        20,
        12,
        {14, 17, 22, 22},
        {1, 1, 2, 2},
    },

    {
        "create water",
        spell_create_water,
        nullptr,
        "",
        "!Create Water!",
        nullptr,
        nullptr,
        0,
        TAR_OBJ_INV,
        Position::Type::Standing,
        SLOT(13),
        5,
        12,
        {8, 3, 12, 11},
        {1, 1, 2, 2},
    },

    {
        "cure blindness",
        spell_cure_blindness,
        nullptr,
        "",
        "!Cure Blindness!",
        nullptr,
        nullptr,
        0,
        TAR_CHAR_DEFENSIVE,
        Position::Type::Fighting,
        SLOT(14),
        5,
        12,
        {60, 6, 8, 10},
        {1, 1, 2, 2},
    },

    {
        "cure critical",
        spell_cure_critical,
        nullptr,
        "",
        "!Cure Critical!",
        nullptr,
        nullptr,
        0,
        TAR_CHAR_DEFENSIVE,
        Position::Type::Fighting,
        SLOT(15),
        20,
        12,
        {60, 13, 17, 60},
        {1, 1, 2, 2},
    },

    {
        "cure disease",
        spell_cure_disease,
        nullptr,
        "",
        "!Cure Disease!",
        nullptr,
        nullptr,
        0,
        TAR_CHAR_DEFENSIVE,
        Position::Type::Standing,
        SLOT(501),
        20,
        12,
        {60, 13, 14, 17},
        {1, 1, 2, 2},
    },

    {
        "cure light",
        spell_cure_light,
        nullptr,
        "",
        "!Cure Light!",
        nullptr,
        nullptr,
        0,
        TAR_CHAR_DEFENSIVE,
        Position::Type::Fighting,
        SLOT(16),
        10,
        12,
        {60, 1, 3, 60},
        {1, 1, 2, 2},
    },

    {
        "cure poison",
        spell_cure_poison,
        nullptr,
        "",
        "!Cure Poison!",
        nullptr,
        nullptr,
        0,
        TAR_CHAR_DEFENSIVE,
        Position::Type::Standing,
        SLOT(43),
        5,
        12,
        {60, 14, 16, 19},
        {1, 1, 2, 2},
    },

    {
        "cure serious",
        spell_cure_serious,
        nullptr,
        "",
        "!Cure Serious!",
        nullptr,
        nullptr,
        0,
        TAR_CHAR_DEFENSIVE,
        Position::Type::Fighting,
        SLOT(61),
        15,
        12,
        {60, 7, 10, 60},
        {1, 1, 2, 2},
    },

    {
        "curse",
        spell_curse,
        &gsn_curse,
        "curse",
        "The curse wears off.",
        check_dispel,
        "$n looks relieved.",
        0,
        TAR_CHAR_OFFENSIVE,
        Position::Type::Fighting,
        SLOT(17),
        20,
        12,
        {18, 18, 26, 22},
        {1, 1, 2, 2},
    },

    {
        "exorcise",
        spell_exorcise,
        nullptr,
        "exorcism",
        "!exorcise!",
        nullptr,
        nullptr,
        0,
        TAR_CHAR_OFFENSIVE,
        Position::Type::Fighting,
        SLOT(506),
        20,
        12,
        {60, 34, 40, 60},
        {1, 1, 2, 2},
    },

    {
        "demonfire",
        spell_demonfire,
        nullptr,
        "malice",
        "!Demonfire!",
        nullptr,
        nullptr,
        0,
        TAR_CHAR_OFFENSIVE,
        Position::Type::Fighting,
        SLOT(505),
        20,
        12,
        {60, 34, 40, 60},
        {1, 1, 2, 2},
    },

    {
        "detect evil",
        spell_detect_evil,
        nullptr,
        "",
        "The red in your vision disappears.",
        check_dispel,
        "$n's sensitivity to evil fades.",
        AFF_DETECT_EVIL,
        TAR_CHAR_SELF,
        Position::Type::Standing,
        SLOT(18),
        5,
        12,
        {12, 4, 60, 60},
        {1, 1, 2, 2},
    },

    {
        "detect hidden",
        spell_detect_hidden,
        nullptr,
        "",
        "You feel less aware of your suroundings.",
        check_dispel,
        "$n looks less alert.",
        AFF_DETECT_HIDDEN,
        TAR_CHAR_SELF,
        Position::Type::Standing,
        SLOT(44),
        5,
        12,
        {15, 11, 60, 60},
        {1, 1, 2, 2},
    },

    {
        "detect invis",
        spell_detect_invis,
        nullptr,
        "",
        "You no longer see invisible objects.",
        check_dispel,
        "$n's eyes stop sparkling.",
        AFF_DETECT_INVIS,
        TAR_CHAR_SELF,
        Position::Type::Standing,
        SLOT(19),
        5,
        12,
        {3, 8, 60, 60},
        {1, 1, 2, 2},
    },

    {
        "detect magic",
        spell_detect_magic,
        nullptr,
        "",
        "The detect magic wears off.",
        check_dispel,
        "$n's sensitivity to magic fades.",
        AFF_DETECT_MAGIC,
        TAR_CHAR_SELF,
        Position::Type::Standing,
        SLOT(20),
        5,
        12,
        {2, 6, 60, 60},
        {1, 1, 2, 2},
    },

    {
        "detect poison",
        spell_detect_poison,
        nullptr,
        "",
        "!Detect Poison!",
        check_dispel,
        "$n's sensitivity to poison fades.",
        0,
        TAR_OBJ_INV,
        Position::Type::Standing,
        SLOT(21),
        5,
        12,
        {15, 7, 60, 60},
        {1, 1, 2, 2},
    },

    {
        "dispel evil",
        spell_dispel_evil,
        nullptr,
        "dispel evil",
        "!Dispel Evil!",
        nullptr,
        nullptr,
        0,
        TAR_CHAR_OFFENSIVE,
        Position::Type::Fighting,
        SLOT(22),
        15,
        12,
        {60, 15, 20, 60},
        {1, 1, 2, 2},
    },

    {
        "dispel good",
        spell_dispel_good,
        nullptr,
        "dispel good",
        "!Dispel Good!",
        nullptr,
        nullptr,
        0,
        TAR_CHAR_OFFENSIVE,
        Position::Type::Fighting,
        SLOT(322),
        15,
        12,
        {60, 15, 20, 60},
        {1, 1, 2, 2},
    },

    {
        "dispel magic",
        spell_dispel_magic,
        nullptr,
        "",
        "!Dispel Magic!",
        nullptr,
        nullptr,
        0,
        TAR_CHAR_OFFENSIVE,
        Position::Type::Fighting,
        SLOT(59),
        15,
        12,
        {16, 24, 30, 30},
        {1, 1, 2, 2},
    },

    {
        "earthquake",
        spell_earthquake,
        nullptr,
        "earthquake",
        "!Earthquake!",
        nullptr,
        nullptr,
        0,
        TAR_IGNORE,
        Position::Type::Fighting,
        SLOT(23),
        15,
        12,
        {60, 10, 14, 60},
        {1, 1, 2, 2},
    },

    {
        "enchant armor",
        spell_enchant_armor,
        nullptr,
        "",
        "!Enchant Armor!",
        nullptr,
        nullptr,
        0,
        TAR_OBJ_INV,
        Position::Type::Standing,
        SLOT(510),
        100,
        24,
        {16, 60, 60, 60},
        {1, 1, 2, 2},
    },

    {
        "protect container",
        spell_protect_container,
        nullptr,
        "",
        "!Protect Container!",
        nullptr,
        nullptr,
        0,
        TAR_OBJ_INV,
        Position::Type::Standing,
        SLOT(606),
        50,
        24,
        {50, 50, 50, 50},
        {1, 1, 2, 2},
    },

    {
        "venom",
        spell_venom,
        nullptr,
        "",
        "!Venom!",
        nullptr,
        nullptr,
        0,
        TAR_OBJ_INV,
        Position::Type::Standing,
        SLOT(600),
        50,
        24,
        {60, 60, 60, 10},
        {1, 1, 2, 1},
    },

    {
        "vorpal",
        spell_vorpal,
        nullptr,
        "",
        "!Venom!",
        nullptr,
        nullptr,
        0,
        TAR_OBJ_INV,
        Position::Type::Standing,
        SLOT(608),
        50,
        24,
        {93, 93, 93, 93},
        {1, 1, 1, 1},
    },

    {
        "vampire",
        spell_vampire,
        nullptr,
        "",
        "!Vampire!",
        nullptr,
        nullptr,
        0,
        TAR_OBJ_INV,
        Position::Type::Standing,
        SLOT(605),
        50,
        24,
        {93, 93, 93, 93},
        {1, 1, 2, 1},
    },

    {
        "black death",
        spell_black_death,
        nullptr,
        "",
        "!Black Death!",
        nullptr,
        nullptr,
        0,
        TAR_OBJ_INV,
        Position::Type::Standing,
        SLOT(601),
        100,
        24,
        {60, 60, 60, 35},
        {2, 2, 2, 1},
    },

    {
        "tame lightning",
        spell_tame_lightning,
        nullptr,
        "",
        "!Tame Lightning!",
        nullptr,
        nullptr,
        0,
        TAR_OBJ_INV,
        Position::Type::Standing,
        SLOT(602),
        75,
        24,
        {60, 60, 60, 20},
        {2, 2, 2, 1},
    },

    {
        "acid wash",
        spell_acid_wash,
        nullptr,
        "",
        "!Acid Wash!",
        nullptr,
        nullptr,
        0,
        TAR_OBJ_INV,
        Position::Type::Standing,
        SLOT(603),
        150,
        24,
        {60, 60, 60, 45},
        {2, 2, 2, 1},
    },

    {
        "damnation",
        spell_damnation,
        nullptr,
        "",
        "!Damnation!",
        nullptr,
        nullptr,
        0,
        TAR_OBJ_INV,
        Position::Type::Standing,
        SLOT(604),
        200,
        24,
        {60, 60, 60, 50},
        {2, 2, 2, 1},
    },

    {
        "enchant weapon",
        spell_enchant_weapon,
        nullptr,
        "",
        "!Enchant Weapon!",
        nullptr,
        nullptr,
        0,
        TAR_OBJ_INV,
        Position::Type::Standing,
        SLOT(24),
        100,
        24,
        {17, 60, 60, 60},
        {1, 1, 2, 2},
    },

    {
        "energy drain",
        spell_energy_drain,
        nullptr,
        "energy drain",
        "!Energy Drain!",
        nullptr,
        nullptr,
        0,
        TAR_CHAR_OFFENSIVE,
        Position::Type::Fighting,
        SLOT(25),
        35,
        12,
        {19, 22, 26, 23},
        {1, 1, 2, 2},
    },

    {
        "insanity",
        spell_insanity,
        &gsn_insanity,
        "insanity",
        "Your mind clears.",
        check_dispel,
        "$n looks less confused.",
        0,
        TAR_CHAR_OFFENSIVE,
        Position::Type::Fighting,
        SLOT(206),
        35,
        12,
        {16, 18, 23, 20},
        {1, 1, 2, 2},
    },

    {
        "faerie fire",
        spell_faerie_fire,
        nullptr,
        "faerie fire",
        "The pink aura around you fades away.",
        check_dispel,
        "$n's outline fades.",
        0,
        TAR_CHAR_OFFENSIVE,
        Position::Type::Fighting,
        SLOT(72),
        5,
        12,
        {6, 3, 5, 8},
        {1, 1, 2, 2},
    },

    {
        "faerie fog",
        spell_faerie_fog,
        nullptr,
        "faerie fog",
        "!Faerie Fog!",
        nullptr,
        nullptr,
        0,
        TAR_IGNORE,
        Position::Type::Standing,
        SLOT(73),
        12,
        12,
        {14, 21, 16, 24},
        {1, 1, 2, 2},
    },

    {
        "fireball",
        spell_fireball,
        nullptr,
        "fireball",
        "!Fireball!",
        nullptr,
        nullptr,
        0,
        TAR_CHAR_OFFENSIVE,
        Position::Type::Fighting,
        SLOT(26),
        15,
        12,
        {22, 60, 60, 60},
        {1, 1, 2, 2},
    },

    {
        "flamestrike",
        spell_flamestrike,
        nullptr,
        "flamestrike",
        "!Flamestrike!",
        nullptr,
        nullptr,
        0,
        TAR_CHAR_OFFENSIVE,
        Position::Type::Fighting,
        SLOT(65),
        20,
        12,
        {60, 20, 27, 60},
        {1, 1, 2, 2},
    },

    {
        "fly",
        spell_fly,
        nullptr,
        "",
        "You slowly float to the ground.",
        check_dispel,
        "$n falls to the ground!",
        AFF_FLYING,
        TAR_CHAR_DEFENSIVE,
        Position::Type::Standing,
        SLOT(56),
        10,
        18,
        {10, 18, 20, 22},
        {1, 1, 2, 2},
    },

    {
        "frenzy",
        spell_frenzy,
        nullptr,
        "",
        "Your rage ebbs.",
        check_dispel,
        "$n no longer looks frenzied.",
        AFF_BERSERK,
        TAR_CHAR_DEFENSIVE,
        Position::Type::Standing,
        SLOT(504),
        30,
        24,
        {60, 24, 26, 60},
        {1, 1, 2, 2},
    },

    {
        "gate",
        spell_gate,
        nullptr,
        "",
        "!Gate!",
        nullptr,
        nullptr,
        0,
        TAR_IGNORE,
        Position::Type::Fighting,
        SLOT(83),
        80,
        12,
        {27, 17, 28, 28},
        {1, 1, 2, 2},
    },

    {
        "giant strength",
        spell_giant_strength,
        nullptr,
        "",
        "You feel weaker.",
        check_dispel,
        "$n no longer looks so mighty.",
        0,
        TAR_CHAR_DEFENSIVE,
        Position::Type::Standing,
        SLOT(39),
        20,
        12,
        {11, 19, 22, 16},
        {1, 1, 2, 2},
    },

    {
        "harm",
        spell_harm,
        nullptr,
        "harm spell",
        "!Harm!",
        nullptr,
        nullptr,
        0,
        TAR_CHAR_OFFENSIVE,
        Position::Type::Fighting,
        SLOT(27),
        35,
        12,
        {60, 23, 26, 60},
        {1, 1, 2, 2},
    },

    {
        "haste",
        spell_haste,
        nullptr,
        "",
        "You feel yourself slow down.",
        check_dispel,
        "$n's movements slow down.",
        AFF_HASTE,
        TAR_CHAR_DEFENSIVE,
        Position::Type::Fighting,
        SLOT(502),
        30,
        12,
        {21, 29, 27, 26},
        {1, 1, 2, 2},
    },

    {
        "regeneration",
        spell_regeneration,
        nullptr,
        "You feel vibrant!",
        "You feel less vibrant.",
        check_dispel,
        "The warm glow surrounding $n fades.",
        AFF_REGENERATION,
        TAR_CHAR_DEFENSIVE,
        Position::Type::Standing,
        SLOT(511),
        12,
        12,
        {17, 21, 20, 19},
        {1, 1, 2, 2},
    },

    {
        "lethargy",
        spell_lethargy,
        nullptr,
        "",
        "Your heart-beat quickens.",
        check_dispel,
        "$n looks livelier.",
        0,
        TAR_CHAR_OFFENSIVE,
        Position::Type::Fighting,
        SLOT(208),
        30,
        12,
        {21, 29, 27, 26},
        {1, 1, 2, 2},
    },

    {
        "heal",
        spell_heal,
        nullptr,
        "",
        "!Heal!",
        nullptr,
        nullptr,
        0,
        TAR_CHAR_DEFENSIVE,
        Position::Type::Fighting,
        SLOT(28),
        50,
        12,
        {60, 21, 29, 60},
        {1, 1, 2, 2},
    },

    {
        "holy word",
        spell_holy_word,
        nullptr,
        "divine wrath",
        "!Holy Word!",
        nullptr,
        nullptr,
        0,
        TAR_IGNORE,
        Position::Type::Fighting,
        SLOT(506),
        100,
        24,
        {60, 45, 50, 60},
        {2, 2, 4, 4},
    },

    {
        "identify",
        spell_identify,
        nullptr,
        "",
        "!Identify!",
        nullptr,
        nullptr,
        0,
        TAR_OBJ_INV,
        Position::Type::Standing,
        SLOT(53),
        12,
        24,
        {15, 16, 60, 60},
        {1, 1, 2, 2},
    },

    {
        "infravision",
        spell_infravision,
        nullptr,
        "",
        "You no longer see in the dark.",
        check_dispel,
        "$n's eyes stop glowing red.",
        AFF_INFRARED,
        TAR_CHAR_DEFENSIVE,
        Position::Type::Standing,
        SLOT(77),
        5,
        18,
        {9, 13, 15, 11},
        {1, 1, 2, 2},
    },

    {
        "invis",
        spell_invis,
        &gsn_invis,
        "",
        "You are no longer invisible.",
        check_dispel,
        "$n fades into existence.",
        AFF_INVISIBLE,
        TAR_CHAR_DEFENSIVE,
        Position::Type::Standing,
        SLOT(29),
        5,
        12,
        {5, 60, 60, 60},
        {1, 1, 2, 2},
    },

    {
        "know alignment",
        spell_know_alignment,
        nullptr,
        "",
        "!Know Alignment!",
        nullptr,
        nullptr,
        0,
        TAR_CHAR_DEFENSIVE,
        Position::Type::Fighting,
        SLOT(58),
        9,
        12,
        {12, 9, 60, 60},
        {1, 1, 2, 2},
    },

    {
        "lightning bolt",
        spell_lightning_bolt,
        nullptr,
        "lightning bolt",
        "!Lightning Bolt!",
        nullptr,
        nullptr,
        0,
        TAR_CHAR_OFFENSIVE,
        Position::Type::Fighting,
        SLOT(30),
        15,
        12,
        {13, 23, 18, 22},
        {1, 1, 2, 2},
    },

    {
        "locate object",
        spell_locate_object,
        nullptr,
        "",
        "!Locate Object!",
        nullptr,
        nullptr,
        0,
        TAR_IGNORE,
        Position::Type::Standing,
        SLOT(31),
        20,
        18,
        {9, 15, 60, 60},
        {1, 1, 2, 2},
    },

    {
        "magic missile",
        spell_magic_missile,
        nullptr,
        "magic missile",
        "!Magic Missile!",
        nullptr,
        nullptr,
        0,
        TAR_CHAR_OFFENSIVE,
        Position::Type::Fighting,
        SLOT(32),
        15,
        12,
        {1, 60, 60, 60},
        {1, 1, 2, 2},
    },

    {
        "mass healing",
        spell_mass_healing,
        nullptr,
        "",
        "!Mass Healing!",
        nullptr,
        nullptr,
        0,
        TAR_IGNORE,
        Position::Type::Standing,
        SLOT(508),
        100,
        36,
        {60, 38, 45, 60},
        {2, 2, 4, 4},
    },

    {
        "mass invis",
        spell_mass_invis,
        &gsn_mass_invis,
        "",
        "You are no longer invisible.",
        check_dispel,
        "$n fades into existence.",
        0,
        TAR_IGNORE,
        Position::Type::Standing,
        SLOT(69),
        20,
        24,
        {22, 60, 60, 60},
        {1, 1, 2, 2},
    },

    {
        "pass door",
        spell_pass_door,
        nullptr,
        "",
        "You feel solid again.",
        check_dispel,
        "$n drifts back into phase.",
        AFF_PASS_DOOR,
        TAR_CHAR_DEFENSIVE,
        Position::Type::Standing,
        SLOT(74),
        20,
        12,
        {24, 30, 28, 34},
        {1, 1, 2, 2},
    },

    {
        "plague",
        spell_plague,
        &gsn_plague,
        "sickness",
        "Your sores vanish.",
        nullptr,
        nullptr,
        0,
        TAR_CHAR_OFFENSIVE,
        Position::Type::Fighting,
        SLOT(503),
        20,
        12,
        {23, 17, 36, 26},
        {1, 1, 2, 2},
    },

    {
        "poison",
        spell_poison,
        &gsn_poison,
        "poison",
        "You feel less sick.",
        nullptr,
        nullptr,
        0,
        TAR_CHAR_OFFENSIVE,
        Position::Type::Fighting,
        SLOT(33),
        10,
        12,
        {17, 12, 15, 21},
        {1, 1, 2, 2},
    },

    {
        "portal",
        spell_portal,
        nullptr,
        "",
        "",
        nullptr,
        nullptr,
        0,
        TAR_IGNORE,
        Position::Type::Standing,
        SLOT(516),
        100,
        12,
        {40, 40, 40, 40},
        {1, 1, 2, 2},
    },

    {
        "protection evil",
        spell_protection_evil,
        nullptr,
        "",
        "You feel less protected from evil.",
        check_dispel,
        "$n looks less protected from the forces of evil.",
        AFF_PROTECTION_EVIL,
        TAR_CHAR_SELF,
        Position::Type::Standing,
        SLOT(34),
        5,
        12,
        {12, 9, 12, 12},
        {1, 1, 2, 2},
    },

    {
        "protection good",
        spell_protection_good,
        nullptr,
        "",
        "You feel less protected from good.",
        check_dispel,
        "$n looks less protected from the powers of good.",
        AFF_PROTECTION_GOOD,
        TAR_CHAR_SELF,
        Position::Type::Standing,
        SLOT(607),
        5,
        12,
        {12, 9, 12, 12},
        {1, 1, 2, 2},
    },

    {
        "psychic tornado",
        spell_psy_tornado,
        nullptr,
        "psychic tornado",
        "You regain your senses.",
        nullptr,
        nullptr,
        0,
        TAR_CHAR_OFFENSIVE,
        Position::Type::Standing,
        SLOT(207),
        100,
        16,
        {60, 50, 70, 70},
        {1, 1, 2, 2},
    },

    {
        "refresh",
        spell_refresh,
        nullptr,
        "refresh",
        "!Refresh!",
        nullptr,
        nullptr,
        0,
        TAR_CHAR_DEFENSIVE,
        Position::Type::Standing,
        SLOT(81),
        12,
        18,
        {8, 5, 12, 9},
        {1, 1, 2, 2},
    },

    {
        "remove curse",
        spell_remove_curse,
        nullptr,
        "",
        "!Remove Curse!",
        nullptr,
        nullptr,
        0,
        TAR_CHAR_DEFENSIVE,
        Position::Type::Standing,
        SLOT(35),
        5,
        12,
        {60, 18, 40, 60},
        {1, 1, 2, 2},
    },

    {
        "remove alignment",
        spell_remove_alignment,
        nullptr,
        "",
        "!Remove Alignment!",
        nullptr,
        nullptr,
        0,
        TAR_OBJ_INV,
        Position::Type::Standing,
        SLOT(512),
        100,
        12,
        {60, 18, 60, 60},
        {1, 1, 2, 2},
    },

    {
        "remove invisible",
        spell_remove_invisible,
        nullptr,
        "",
        "!Remove Invisible!",
        nullptr,
        nullptr,
        0,
        TAR_OBJ_INV,
        Position::Type::Standing,
        SLOT(513),
        30,
        12,
        {60, 18, 60, 60},
        {1, 1, 2, 2},
    },

    {
        "talon",
        spell_talon,
        nullptr,
        "",
        "Your hands return to normal.",
        check_dispel,
        "$n's hands return to normal.",
        AFF_TALON,
        TAR_CHAR_DEFENSIVE,
        Position::Type::Standing,
        SLOT(37),
        28,
        12,
        {40, 40, 40, 40},
        {1, 1, 2, 2},
    },

    {
        "sanctuary",
        spell_sanctuary,
        nullptr,
        "",
        "The white aura around your body fades.",
        check_dispel,
        "The white aura around $n's body vanishes.",
        AFF_SANCTUARY,
        TAR_CHAR_DEFENSIVE,
        Position::Type::Standing,
        SLOT(36),
        75,
        12,
        {36, 20, 30, 37},
        {1, 1, 2, 2},
    },

    {
        "shield",
        spell_shield,
        nullptr,
        "",
        "Your force shield shimmers then fades away.",
        check_dispel,
        "The force shield protecting $n vanishes",
        0,
        TAR_CHAR_DEFENSIVE,
        Position::Type::Standing,
        SLOT(67),
        12,
        18,
        {20, 35, 35, 34},
        {1, 1, 2, 2},
    },

    {
        "shocking grasp",
        spell_shocking_grasp,
        nullptr,
        "shocking grasp",
        "!Shocking Grasp!",
        nullptr,
        nullptr,
        0,
        TAR_CHAR_OFFENSIVE,
        Position::Type::Fighting,
        SLOT(53),
        15,
        12,
        {10, 60, 60, 60},
        {1, 1, 2, 2},
    },

    {
        "sleep",
        spell_sleep,
        &gsn_sleep,
        "",
        "You feel less tired.",
        check_dispel,
        "$n looks less sleepy.",
        0,
        TAR_CHAR_OFFENSIVE,
        Position::Type::Standing,
        SLOT(38),
        15,
        12,
        {10, 60, 60, 60},
        {1, 1, 2, 2},
    },

    {
        "stone skin",
        spell_stone_skin,
        nullptr,
        "",
        "Your skin feels soft again.",
        check_dispel,
        "$n's skin regains its normal texture.",
        0,
        TAR_CHAR_SELF,
        Position::Type::Standing,
        SLOT(66),
        12,
        18,
        {25, 40, 40, 45},
        {1, 1, 2, 2},
    },

    {
        "summon",
        spell_summon,
        nullptr,
        "",
        "!Summon!",
        nullptr,
        nullptr,
        0,
        TAR_IGNORE,
        Position::Type::Standing,
        SLOT(40),
        50,
        12,
        {24, 12, 29, 30},
        {1, 1, 2, 2},
    },

    {
        "teleport",
        spell_teleport,
        nullptr,
        "",
        "!Teleport!",
        nullptr,
        nullptr,
        0,
        TAR_CHAR_SELF,
        Position::Type::Fighting,
        SLOT(2),
        35,
        12,
        {13, 22, 25, 36},
        {1, 1, 2, 2},
    },

    {
        "teleport object",
        spell_teleport_object,
        nullptr,
        "",
        "!Teleport Object!",
        nullptr,
        nullptr,
        0,
        TAR_CHAR_OTHER,
        Position::Type::Standing,
        SLOT(205),
        35,
        12,
        {60, 60, 60, 60},
        {1, 1, 2, 2},
    },

    {
        "undo spell",
        spell_undo_spell,
        nullptr,
        "",
        "!Undo Spell!",
        nullptr,
        nullptr,
        0,
        TAR_CHAR_OTHER,
        Position::Type::Fighting,
        SLOT(199),
        12,
        12,
        {60, 60, 60, 60},
        {1, 1, 2, 2},
    },

    {
        "ventriloquate",
        spell_ventriloquate,
        nullptr,
        "",
        "!Ventriloquate!",
        nullptr,
        nullptr,
        0,
        TAR_IGNORE,
        Position::Type::Standing,
        SLOT(41),
        5,
        12,
        {1, 60, 60, 60},
        {1, 1, 2, 2},
    },

    {
        "weaken",
        spell_weaken,
        nullptr,
        "spell",
        "You feel stronger.",
        check_dispel,
        "$n looks stronger.",
        0,
        TAR_CHAR_OFFENSIVE,
        Position::Type::Fighting,
        SLOT(68),
        20,
        12,
        {11, 14, 16, 17},
        {1, 1, 2, 2},
    },

    {
        "word of recall",
        spell_word_of_recall,
        nullptr,
        "",
        "!Word of Recall!",
        nullptr,
        nullptr,
        0,
        TAR_CHAR_SELF,
        Position::Type::Resting,
        SLOT(42),
        5,
        12,
        {32, 28, 32, 33},
        {1, 1, 2, 2},
    },

    /*
     * Dragon breath
     */
    {
        "acid breath",
        spell_acid_breath,
        nullptr,
        "blast of acid",
        "!Acid Breath!",
        nullptr,
        nullptr,
        0,
        TAR_CHAR_OFFENSIVE,
        Position::Type::Fighting,
        SLOT(200),
        12,
        12,
        {42, 44, 46, 48},
        {1, 1, 2, 2},
    },

    {
        "fire breath",
        spell_fire_breath,
        nullptr,
        "blast of flame",
        "!Fire Breath!",
        nullptr,
        nullptr,
        0,
        TAR_CHAR_OFFENSIVE,
        Position::Type::Fighting,
        SLOT(201),
        12,
        12,
        {38, 40, 42, 44},
        {1, 1, 2, 2},
    },

    {
        "frost breath",
        spell_frost_breath,
        nullptr,
        "blast of frost",
        "!Frost Breath!",
        nullptr,
        nullptr,
        0,
        TAR_CHAR_OFFENSIVE,
        Position::Type::Fighting,
        SLOT(202),
        12,
        12,
        {30, 32, 34, 36},
        {1, 1, 2, 2},
    },

    {
        "gas breath",
        spell_gas_breath,
        nullptr,
        "blast of gas",
        "!Gas Breath!",
        nullptr,
        nullptr,
        0,
        TAR_IGNORE,
        Position::Type::Fighting,
        SLOT(203),
        12,
        12,
        {46, 48, 50, 52},
        {1, 1, 2, 2},
    },

    {
        "lightning breath",
        spell_lightning_breath,
        nullptr,
        "blast of lightning",
        "!Lightning Breath!",
        nullptr,
        nullptr,
        0,
        TAR_CHAR_OFFENSIVE,
        Position::Type::Fighting,
        SLOT(204),
        12,
        12,
        {34, 36, 38, 40},
        {1, 1, 2, 2},
    },

    /*
     * Spells for mega1.are from Glop/Erkenbrand.
     */
    {
        "general purpose",
        spell_general_purpose,
        nullptr,
        "general purpose ammo",
        "!General Purpose Ammo!",
        nullptr,
        nullptr,
        0,
        TAR_CHAR_OFFENSIVE,
        Position::Type::Fighting,
        SLOT(401),
        0,
        12,
        {53, 53, 53, 53},
        {0, 0, 0, 0},
    },

    {
        "high explosive",
        spell_high_explosive,
        nullptr,
        "high explosive ammo",
        "!High Explosive Ammo!",
        nullptr,
        nullptr,
        0,
        TAR_CHAR_OFFENSIVE,
        Position::Type::Fighting,
        SLOT(402),
        0,
        12,
        {53, 53, 53, 53},
        {0, 0, 0, 0},
    },

    /* combat and weapons skills */

    {
        "axe",
        spell_null,
        &gsn_axe,
        "",
        "!Axe!",
        nullptr,
        nullptr,
        0,
        TAR_IGNORE,
        Position::Type::Fighting,
        SLOT(0),
        0,
        0,
        {1, 1, 1, 1},
        {6, 6, 4, 2},
    },

    {
        "dagger",
        spell_null,
        &gsn_dagger,
        "",
        "!Dagger!",
        nullptr,
        nullptr,
        0,
        TAR_IGNORE,
        Position::Type::Fighting,
        SLOT(0),
        0,
        0,
        {1, 1, 1, 1},
        {2, 3, 2, 3},
    },

    {
        "flail",
        spell_null,
        &gsn_flail,
        "",
        "!Flail!",
        nullptr,
        nullptr,
        0,
        TAR_IGNORE,
        Position::Type::Fighting,
        SLOT(0),
        0,
        0,
        {1, 1, 1, 1},
        {6, 3, 4, 5},
    },

    {
        "mace",
        spell_null,
        &gsn_mace,
        "",
        "!Mace!",
        nullptr,
        nullptr,
        0,
        TAR_IGNORE,
        Position::Type::Fighting,
        SLOT(0),
        0,
        0,
        {1, 1, 1, 1},
        {5, 2, 3, 3},
    },

    {
        "polearm",
        spell_null,
        &gsn_polearm,
        "",
        "!Polearm!",
        nullptr,
        nullptr,
        0,
        TAR_IGNORE,
        Position::Type::Fighting,
        SLOT(0),
        0,
        0,
        {1, 1, 1, 1},
        {6, 6, 4, 6},
    },

    {
        "shield block",
        spell_null,
        &gsn_shield_block,
        "",
        "!Shield!",
        nullptr,
        nullptr,
        0,
        TAR_IGNORE,
        Position::Type::Fighting,
        SLOT(0),
        0,
        0,
        {1, 1, 1, 1},
        {6, 4, 3, 2},
    },

    {
        "spear",
        spell_null,
        &gsn_spear,
        "",
        "!Spear!",
        nullptr,
        nullptr,
        0,
        TAR_IGNORE,
        Position::Type::Fighting,
        SLOT(0),
        0,
        0,
        {1, 1, 1, 1},
        {4, 4, 4, 3},
    },

    {
        "sword",
        spell_null,
        &gsn_sword,
        "",
        "!sword!",
        nullptr,
        nullptr,
        0,
        TAR_IGNORE,
        Position::Type::Fighting,
        SLOT(0),
        0,
        0,
        {1, 1, 1, 1},
        {8, 6, 2, 4},
    },

    {
        "whip",
        spell_null,
        &gsn_whip,
        "",
        "!Whip!",
        nullptr,
        nullptr,
        0,
        TAR_IGNORE,
        Position::Type::Fighting,
        SLOT(0),
        0,
        0,
        {1, 1, 1, 1},
        {6, 5, 5, 4},
    },

    {
        "backstab",
        spell_null,
        &gsn_backstab,
        "backstab",
        "!Backstab!",
        nullptr,
        nullptr,
        0,
        TAR_IGNORE,
        Position::Type::Standing,
        SLOT(0),
        0,
        24,
        {30, 30, 30, 30},
        {SKILL_ASSASSIN, SKILL_ASSASSIN, SKILL_ASSASSIN, SKILL_ASSASSIN},
    },

    {
        "bash",
        spell_null,
        &gsn_bash,
        "bash",
        "!Bash!",
        nullptr,
        nullptr,
        0,
        TAR_IGNORE,
        Position::Type::Fighting,
        SLOT(0),
        0,
        24,
        {60, 60, 5, 1},
        {SKILL_ATTAINABLE, SKILL_ATTAINABLE, 3, 2},
    },

    {
        "berserk",
        spell_null,
        &gsn_berserk,
        "",
        "You feel your pulse slow down.",
        nullptr,
        nullptr,
        0,
        TAR_IGNORE,
        Position::Type::Fighting,
        SLOT(0),
        0,
        24,
        {60, 60, 25, 15},
        {SKILL_ATTAINABLE, SKILL_ATTAINABLE, 6, 4},
    },

    {
        "dirt kicking",
        spell_null,
        &gsn_dirt,
        "kicked dirt",
        "You rub the dirt out of your eyes.",
        nullptr,
        nullptr,
        0,
        TAR_IGNORE,
        Position::Type::Fighting,
        SLOT(0),
        0,
        24,
        {60, 60, 6, 3},
        {SKILL_ATTAINABLE, SKILL_ATTAINABLE, 5, 4},
    },

    {
        "disarm",
        spell_null,
        &gsn_disarm,
        "",
        "!Disarm!",
        nullptr,
        nullptr,
        0,
        TAR_IGNORE,
        Position::Type::Fighting,
        SLOT(0),
        0,
        24,
        {60, 60, 6, 11},
        {SKILL_ATTAINABLE, SKILL_ATTAINABLE, 4, 6},
    },

    {
        "dodge",
        spell_null,
        &gsn_dodge,
        "",
        "!Dodge!",
        nullptr,
        nullptr,
        0,
        TAR_IGNORE,
        Position::Type::Fighting,
        SLOT(0),
        0,
        0,
        {20, 22, 5, 1},
        {8, 8, 8, 6},
    },

    {
        "enhanced damage",
        spell_null,
        &gsn_enhanced_damage,
        "",
        "!Enhanced Damage!",
        nullptr,
        nullptr,
        0,
        TAR_IGNORE,
        Position::Type::Fighting,
        SLOT(0),
        0,
        0,
        {60, 60, 5, 1},
        {SKILL_ATTAINABLE, 9, 5, 3},
    },

    {
        "hand to hand",
        spell_null,
        &gsn_hand_to_hand,
        "",
        "!Hand to Hand!",
        nullptr,
        nullptr,
        0,
        TAR_IGNORE,
        Position::Type::Fighting,
        SLOT(0),
        0,
        0,
        {25, 10, 10, 6},
        {8, 5, 4, 3},
    },

    {
        "kick",
        spell_null,
        &gsn_kick,
        "kick",
        "!Kick!",
        nullptr,
        nullptr,
        0,
        TAR_CHAR_OFFENSIVE,
        Position::Type::Fighting,
        SLOT(0),
        0,
        12,
        {60, 12, 12, 8},
        {SKILL_ATTAINABLE, 4, 4, 3},
    },

    {
        "headbutt",
        spell_null,
        &gsn_headbutt,
        "headbutt",
        "You wipe the blood from your eyes.",
        nullptr,
        nullptr,
        0,
        TAR_CHAR_OFFENSIVE,
        Position::Type::Fighting,
        SLOT(0),
        0,
        12,
        {60, 60, 20, 5},
        {SKILL_ATTAINABLE, SKILL_ATTAINABLE, 8, 3},
    },

    {
        "parry",
        spell_null,
        &gsn_parry,
        "",
        "!Parry!",
        nullptr,
        nullptr,
        0,
        TAR_IGNORE,
        Position::Type::Fighting,
        SLOT(0),
        0,
        0,
        {22, 20, 1, 5},
        {8, 8, 4, 5},
    },

    {
        "rescue",
        spell_null,
        &gsn_rescue,
        "",
        "!Rescue!",
        nullptr,
        nullptr,
        0,
        TAR_IGNORE,
        Position::Type::Fighting,
        SLOT(0),
        0,
        12,
        {60, 60, 3, 1},
        {SKILL_ATTAINABLE, 6, 2, 4},
    },

    {
        "trip",
        spell_null,
        &gsn_trip,
        "trip",
        "!Trip!",
        nullptr,
        nullptr,
        0,
        TAR_IGNORE,
        Position::Type::Fighting,
        SLOT(0),
        0,
        24,
        {60, 60, 1, 1},
        {SKILL_ATTAINABLE, SKILL_ATTAINABLE, 4, 3},
    },

    {
        "second attack",
        spell_null,
        &gsn_second_attack,
        "",
        "!Second Attack!",
        nullptr,
        nullptr,
        0,
        TAR_IGNORE,
        Position::Type::Fighting,
        SLOT(0),
        0,
        0,
        {30, 24, 7, 5},
        {10, 8, 4, 3},
    },

    {
        "third attack",
        spell_null,
        &gsn_third_attack,
        "",
        "!Third Attack!",
        nullptr,
        nullptr,
        0,
        TAR_IGNORE,
        Position::Type::Fighting,
        SLOT(0),
        0,
        0,
        {60, 60, 14, 12},
        {SKILL_ATTAINABLE, SKILL_ATTAINABLE, 6, 4},
    },

    /* non-combat skills */

    {
        "fast healing",
        spell_null,
        &gsn_fast_healing,
        "",
        "!Fast Healing!",
        nullptr,
        nullptr,
        0,
        TAR_IGNORE,
        Position::Type::Sleeping,
        SLOT(0),
        0,
        0,
        {15, 9, 8, 6},
        {8, 5, 4, 3},
    },

    {
        "haggle",
        spell_null,
        &gsn_haggle,
        "",
        "!Haggle!",
        nullptr,
        nullptr,
        0,
        TAR_IGNORE,
        Position::Type::Resting,
        SLOT(0),
        0,
        0,
        {7, 18, 10, 14},
        {5, 8, 6, 6},
    },

    {
        "hide",
        spell_null,
        &gsn_hide,
        "",
        "!Hide!",
        nullptr,
        nullptr,
        0,
        TAR_IGNORE,
        Position::Type::Resting,
        SLOT(0),
        0,
        12,
        {30, 30, 30, 30},
        {SKILL_ASSASSIN, SKILL_ASSASSIN, SKILL_ASSASSIN, SKILL_ASSASSIN},
    },

    {
        "lore",
        spell_null,
        &gsn_lore,
        "",
        "!Lore!",
        nullptr,
        nullptr,
        0,
        TAR_IGNORE,
        Position::Type::Resting,
        SLOT(0),
        0,
        36,
        {10, 10, 16, 20},
        {6, 6, 8, 8},
    },

    {
        "meditation",
        spell_null,
        &gsn_meditation,
        "",
        "Meditation",
        nullptr,
        nullptr,
        0,
        TAR_IGNORE,
        Position::Type::Sleeping,
        SLOT(0),
        0,
        0,
        {6, 6, 15, 15},
        {5, 5, 8, 8},
    },

    {
        "peek",
        spell_null,
        &gsn_peek,
        "",
        "!Peek!",
        nullptr,
        nullptr,
        0,
        TAR_IGNORE,
        Position::Type::Standing,
        SLOT(0),
        0,
        0,
        {30, 30, 30, 30},
        {SKILL_ASSASSIN, SKILL_ASSASSIN, SKILL_ASSASSIN, SKILL_ASSASSIN},
    },

    {
        "ride",
        spell_null,
        &gsn_ride,
        "",
        "!Ride!",
        nullptr,
        nullptr,
        0,
        TAR_IGNORE,
        Position::Type::Standing,
        SLOT(0),
        0,
        0,
        {60, 60, 5, 60},
        {SKILL_ATTAINABLE, SKILL_ATTAINABLE, 4, SKILL_ATTAINABLE},
    },

    {
        "sharpen",
        spell_null,
        &gsn_sharpen,
        "",
        "!Sharpen!",
        nullptr,
        nullptr,
        0,
        TAR_OBJ_INV,
        Position::Type::Standing,
        SLOT(0),
        0,
        0,
        {60, 60, 15, 60},
        {SKILL_ATTAINABLE, SKILL_ATTAINABLE, 4, SKILL_ATTAINABLE},
    },

    {
        "pick lock",
        spell_null,
        &gsn_pick_lock,
        "",
        "!Pick!",
        nullptr,
        nullptr,
        0,
        TAR_IGNORE,
        Position::Type::Standing,
        SLOT(0),
        0,
        12,
        {25, 25, 25, 25},
        {5, 5, 5, 5},
    },

    {
        "sneak",
        spell_null,
        &gsn_sneak,
        "",
        "You no longer feel stealthy.",
        nullptr,
        nullptr,
        0,
        TAR_IGNORE,
        Position::Type::Standing,
        SLOT(0),
        0,
        12,
        {30, 30, 30, 30},
        {SKILL_ASSASSIN, SKILL_ASSASSIN, SKILL_ASSASSIN, SKILL_ASSASSIN},
    },

    {
        "steal",
        spell_null,
        &gsn_steal,
        "",
        "!Steal!",
        nullptr,
        nullptr,
        0,
        TAR_IGNORE,
        Position::Type::Standing,
        SLOT(0),
        0,
        24,
        {30, 30, 30, 30},
        {SKILL_ASSASSIN, SKILL_ASSASSIN, SKILL_ASSASSIN, SKILL_ASSASSIN},
    },

    {
        "scrolls",
        spell_null,
        &gsn_scrolls,
        "",
        "!Scrolls!",
        nullptr,
        nullptr,
        0,
        TAR_IGNORE,
        Position::Type::Standing,
        SLOT(0),
        0,
        24,
        {1, 1, 1, 1},
        {2, 3, 6, 8},
    },

    {
        "staves",
        spell_null,
        &gsn_staves,
        "",
        "!Staves!",
        nullptr,
        nullptr,
        0,
        TAR_IGNORE,
        Position::Type::Standing,
        SLOT(0),
        0,
        12,
        {1, 1, 1, 1},
        {2, 3, 6, 8},
    },

    {
        "wands",
        spell_null,
        &gsn_wands,
        "",
        "!Wands!",
        nullptr,
        nullptr,
        0,
        TAR_IGNORE,
        Position::Type::Standing,
        SLOT(0),
        0,
        12,
        {1, 1, 1, 1},
        {2, 3, 6, 8},
    },

    {
        "throw",
        spell_null,
        &gsn_throw,
        "",
        "!Throw!",
        nullptr,
        nullptr,
        0,
        TAR_IGNORE,
        Position::Type::Standing,
        SLOT(0),
        0,
        12,
        {15, 15, 15, 15},
        {2, 2, 3, 5},
    },

    {
        "recall",
        spell_null,
        &gsn_recall,
        "",
        "!Recall!",
        nullptr,
        nullptr,
        0,
        TAR_IGNORE,
        Position::Type::Standing,
        SLOT(0),
        0,
        12,
        {1, 1, 1, 1},
        {2, 2, 2, 2},
    }

    /* commented out for time being --Fara
      {
       "raise dead",      {
          1,  1,  1,  1       }
       ,  {
         SKILL_ATTAINABLE, SKILL_ATTAINABLE,
         SKILL_ATTAINABLE, SKILL_ATTAINABLE }
       ,
       spell_raise_dead,    TAR_IGNORE,    Position::Type::Standing,
       &gsn_raise_dead,      SLOT( 209),   100, 12,
       "",         "!Raise dead!",      nullptr, nullptr, 0
       }, */

};

const struct group_type group_table[MAX_GROUP] = {

    {"rom basics", {0, 0, 0, 0}, {"scrolls", "staves", "wands", "recall", "throw"}},

    {"mage basics", {0, -3, -3, -3}, {"dagger"}},

    {"cleric basics", {-3, 0, -3, -3}, {"mace"}},

    {"knight basics", {-3, -3, 0, -3}, {"sword", "ride"}},

    {"barbarian basics", {-3, -3, -3, 0}, {"axe", "enhanced damage"}},

    {"mage default",
     {40, -3, -3, -3},
     {"lore", "beguiling", "combat", "detection", "enhancement", "illusion", "maledictions", "protective",
      "transportation", "weather"}},

    {"cleric default",
     {-3, 40, -3, -3},
     {"flail", "attack", "creation", "curative", "benedictions", "detection", "healing", "maledictions", "protective",
      "shield block", "transportation", "weather"}},

    {"knight default",
     {-3, -3, 40, -3},
     {"second attack", "shield block", "parry", "rescue", "disarm", "weaponsmaster", "bash"}},

    {"barbarian default",
     {-3, -3, -3, 40},
     {"shield block", "dodge", "berserk", "dirt kick", "second attack", "third attack", "kick", "hand to hand", "trip",
      "weapon craft"}},

    {"assassin", {20, 20, 20, 20}, {"sneak", "hide", "backstab", "steal", "peek", "dagger"}},

    {"weaponsmaster", {40, 35, 20, 25}, {"axe", "dagger", "flail", "mace", "polearm", "spear", "sword", "whip"}},

    {"attack", {-1, 5, 8, -1}, {"demonfire", "dispel evil", "dispel good", "earthquake", "flamestrike", "exorcise"}},

    {"weapon craft", {-1, -1, -1, 8}, {"venom", "tame lightning", "black death", "acid wash", "damnation"}},

    {"beguiling", {4, -1, -1, -1}, {"charm person", "sleep"}},

    {"benedictions",
     {-1, 4, 8, -1},
     {"bless", "calm", "frenzy", "holy word", "remove curse", "remove invisible", "remove alignment"}},

    {"combat",
     {6, -1, -1, -1},
     {"acid blast", "burning hands", "chain lightning", "chill touch", "colour spray", "fireball", "lightning bolt",
      "magic missile", "shocking grasp"}},

    {"creation", {4, 4, 8, 8}, {"continual light", "create food", "create spring", "create water"}},

    {"curative", {-1, 4, 6, 8}, {"cure blindness", "cure disease", "cure poison"}},

    {"detection",
     {4, 3, -1, -1},
     {"detect evil", "detect hidden", "detect invis", "detect magic", "detect poison", "identify", "know alignment",
      "locate object"}},

    {"draconian", {8, -1, -1, -1}, {"acid breath", "fire breath", "frost breath", "gas breath", "lightning breath"}},

    {"enchantment", {6, -1, -1, -1}, {"enchant armor", "enchant weapon"}},

    {"enhancement", {5, -1, 9, 10}, {"giant strength", "haste", "infravision", "refresh", "regeneration"}},

    {"harmful", {-1, 3, 6, -1}, {"cause critical", "cause light", "cause serious", "harm"}},

    {"healing", {-1, 3, 6, -1}, {"cure critical", "cure light", "cure serious", "heal", "mass healing", "refresh"}},

    {"illusion", {4, -1, -1, -1}, {"invis", "mass invis", "ventriloquate"}},

    {"maledictions",
     {5, 5, 8, 10},
     {"blindness", "change sex", "curse", "energy drain", "plague", "poison", "weaken", "lethargy", "insanity"}},

    {"protective",
     {4, 4, 8, 10},
     {"armor", "cancellation", "dispel magic", "protection evil", "sanctuary", "shield", "stone skin",
      "protection good"}},

    {"specialities", {10, 10, 10, 10}, {"teleport object", "undo spell", "protect container", "talon"}},

    {"transportation", {4, 4, 8, 10}, {"fly", "gate", "pass door", "summon", "teleport", "word of recall", "portal"}},

    {"weather",
     {4, 4, 8, 8},
     {"call lightning", "control weather", "faerie fire", "faerie fog", "lightning bolt", "octarine fire",
      "psychic tornado"}}

};
